/* CHEBSEL v1.13.0 — Institutional Operations */
'use strict';
(function(){
 const ALERT_READ_KEY='chebsel_alert_reads_v1';
 const ARCHIVE_CACHE_KEY='chebsel_archive_registry_cache_v1';
 const CONFLICT_CACHE_KEY='chebsel_conflict_registry_cache_v1';
 const CLOSE_HISTORY_CACHE_KEY='chebsel_closing_history_cache_v1';
 let lastAlerts=[];

 function role(){try{return String(currentRoleView?.()||'').toLowerCase()}catch(e){return ''}}
 function responsible(){return ['president','secretary','treasurer'].includes(role())}
 function closingAllowed(){return ['president','treasurer'].includes(role())}
 function esc(s){try{return escapeHtml(String(s??''))}catch(e){return String(s??'')}}
 function nowISO(){return new Date().toISOString()}
 function prevMonth(){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
 function monthRange(m){const [y,mo]=m.split('-').map(Number),last=new Date(y,mo,0).getDate();return {from:`${m}-01`,to:`${m}-${String(last).padStart(2,'0')}`}}
 function sameSnapshot(a,b){const keys=['due','paid','balance','cashIn','expenses','net','debtors'];return keys.every(k=>Number(a?.[k]||0)===Number(b?.[k]||0))}
 async function context(){const c=await getCloudClient(),p=await getCloudProfile(),org=p?.organization_id||p?.org_id,uid=p?.auth_user_id;if(!org||!uid)throw new Error('Session CHEBSEL Cloud incomplète.');return {c,p,org,uid}}
 function localClosings(){return safeParse(CLOSE_KEY)||{}}
 function saveLocalClosings(x){localStorage.setItem(CLOSE_KEY,JSON.stringify(x));try{syncReadyOnLocalWrite(CLOSE_KEY,x)}catch(e){}}
 function institutionalSnapshot(month){const s={...(monthlySnapshot?.(month)||{})},r=monthRange(month);try{const ins=treasuryIncomeRows(r.from,r.to),outs=treasuryExpenseRows(r.from,r.to);s.cashIn=ins.reduce((n,x)=>n+Number(x.amount||0),0);s.expenses=outs.reduce((n,x)=>n+Number(x.amount||0),0);s.net=s.cashIn-s.expenses}catch(e){s.cashIn=Number(s.paid||0);s.expenses=0;s.net=s.cashIn}return s}
 async function history(action,month,note,snapshot){try{const {c,org,uid}=await context();const x=await c.from('chebsel_closing_history').insert({organization_id:org,month_reference:month,action,actor_id:uid,actor_role:role(),note:note||null,snapshot:snapshot||{}});if(x.error)throw x.error}catch(e){console.warn('CHEBSEL closing history:',e)}}
 async function pullInstitutionalClosings(){if(!navigator.onLine||!responsible())return;try{const {c,org}=await context(),q=await c.from('monthly_closings').select('*').eq('organization_id',org);if(q.error)throw q.error;const cls=localClosings();for(const r of q.data||[]){cls[r.month_reference]={...(cls[r.month_reference]||{}),syncId:r.id,status:r.status||((r.closed_at&&!r.reopened_at)?'approved':(r.reopened_at?'reopened':'draft')),preparedAt:r.prepared_at||null,approvedAt:r.approved_at||r.closed_at||null,reopenedAt:r.reopened_at||null,reopenedReason:r.reopened_reason||'',note:r.notes||'',snapshot:r.snapshot||{},locked:(r.status==='approved'||(!r.status&&!!r.closed_at&&!r.reopened_at)),at:r.approved_at||r.closed_at||r.prepared_at||null,by:r.status==='approved'?'Président':(r.status==='prepared'?'Trésorier':'Cloud')}}saveLocalClosings(cls)}catch(e){console.warn('Pull clôtures institutionnelles:',e)}}
 window.pullInstitutionalClosings=pullInstitutionalClosings;

 async function upsertClosing(month,row){const {c,org}=await context();const existing=await c.from('monthly_closings').select('id').eq('organization_id',org).eq('month_reference',month).maybeSingle();if(existing.error)throw existing.error;const payload={...row,organization_id:org,month_reference:month,updated_at:nowISO()};if(existing.data?.id)payload.id=existing.data.id;const q=await c.from('monthly_closings').upsert(payload,{onConflict:existing.data?.id?'id':'organization_id,month_reference'}).select().single();if(q.error)throw q.error;return q.data}

 window.prepareInstitutionalClose=async function(){if(role()!=='treasurer'){alert('Se Trésorier la ki prepare clôture mansyèl la.');return}if(!navigator.onLine){alert('Koneksyon entènèt nesesè pou prepare yon clôture institutionnelle.');return}const month=closeMonth.value;if(!month)return;if(!(await criticalGuard('month.close','Préparer la clôture '+month)))return;const snap=institutionalSnapshot(month),note=(closeNote.value||'').trim();try{const {uid}=await context(),r=await upsertClosing(month,{status:'prepared',prepared_by:uid,prepared_at:nowISO(),approved_by:null,approved_at:null,closed_by:null,closed_at:null,reopened_by:null,reopened_at:null,reopened_reason:null,notes:note||null,snapshot:snap});const cls=localClosings();cls[month]={syncId:r.id,status:'prepared',preparedAt:r.prepared_at,note,snapshot:snap,locked:false,by:'Trésorier'};saveLocalClosings(cls);await history('prepared',month,note,snap);audit('Clôture préparée',month,{entity:'monthly_close',entityId:month,after:cls[month]});await registerChebselArchive('monthly_closing_prepared',`${month}-01`,monthRange(month).to,`Cloture_CHEBSEL_${month}_PREPAREE`,{month,status:'prepared'});renderMonthlyClose();refreshInstitutionalAlerts();alert('Clôture préparée. Li ap tann validation Prezidan an.')}catch(e){alert('Préparation clôture impossible : '+(e?.message||e))}}

 window.approveInstitutionalClose=async function(){if(role()!=='president'){alert('Se Prezidan an sèlman ki valide clôture la.');return}if(!navigator.onLine){alert('Koneksyon entènèt nesesè pou valide clôture la.');return}const month=closeMonth.value;if(!month)return;try{const {c,org,uid}=await context(),q=await c.from('monthly_closings').select('*').eq('organization_id',org).eq('month_reference',month).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='prepared'){alert('Trezorye a dwe prepare mwa sa a anvan Prezidan an valide li.');return}const current=institutionalSnapshot(month);if(!sameSnapshot(q.data.snapshot,current)){alert('Done finansye yo chanje depi Trezorye a te prepare clôture la. Trezorye a dwe prepare li ankò anvan validation.');return}if(!(await criticalGuard('month.close','Valider la clôture '+month)))return;const t=nowISO(),r=await upsertClosing(month,{status:'approved',prepared_by:q.data.prepared_by,prepared_at:q.data.prepared_at,approved_by:uid,approved_at:t,closed_by:uid,closed_at:t,reopened_by:null,reopened_at:null,reopened_reason:null,notes:q.data.notes||null,snapshot:q.data.snapshot});const cls=localClosings();cls[month]={syncId:r.id,status:'approved',preparedAt:r.prepared_at,approvedAt:r.approved_at,note:r.notes||'',snapshot:r.snapshot||{},locked:true,at:r.approved_at,by:'Président'};saveLocalClosings(cls);await history('approved',month,r.notes,r.snapshot);audit('Clôture validée par le Président',month,{entity:'monthly_close',entityId:month,after:cls[month]});await registerChebselArchive('monthly_closing_approved',`${month}-01`,monthRange(month).to,`Cloture_CHEBSEL_${month}_VALIDEE`,{month,status:'approved'});renderMonthlyClose();refreshInstitutionalAlerts();alert('Clôture validée et verrouillée.')}catch(e){alert('Validation clôture impossible : '+(e?.message||e))}}

 window.reopenInstitutionalClose=async function(){if(role()!=='president'){alert('Se Prezidan an sèlman ki ka réouvrir yon mwa.');return}const month=closeMonth.value;if(!month)return;const reason=prompt('Motif obligatoire de réouverture du mois '+month+' :');if(reason===null)return;if(!reason.trim()){alert('Motif la obligatwa.');return}if(!(await criticalGuard('month.reopen','Réouvrir le mois '+month)))return;try{const {c,org,uid}=await context(),q=await c.from('monthly_closings').select('*').eq('organization_id',org).eq('month_reference',month).maybeSingle();if(q.error)throw q.error;if(!q.data||q.data.status!=='approved'){alert('Mwa sa a pa nan eta validé.');return}const t=nowISO(),r=await upsertClosing(month,{status:'reopened',prepared_by:q.data.prepared_by,prepared_at:q.data.prepared_at,approved_by:q.data.approved_by,approved_at:q.data.approved_at,closed_by:q.data.closed_by,closed_at:q.data.closed_at,reopened_by:uid,reopened_at:t,reopened_reason:reason.trim(),notes:q.data.notes||null,snapshot:q.data.snapshot||{}});const cls=localClosings();cls[month]={syncId:r.id,status:'reopened',preparedAt:r.prepared_at,approvedAt:r.approved_at,reopenedAt:r.reopened_at,reopenedReason:reason.trim(),note:r.notes||'',snapshot:r.snapshot||{},locked:false,by:'Président'};saveLocalClosings(cls);await history('reopened',month,reason.trim(),r.snapshot);audit('Mois réouvert',`${month} • ${reason.trim()}`,{entity:'monthly_close',entityId:month,after:cls[month]});renderMonthlyClose();refreshInstitutionalAlerts();alert('Mwa a réouvert. Trezorye a dwe prepare yon nouvo clôture apre koreksyon yo.')}catch(e){alert('Réouverture impossible : '+(e?.message||e))}}

 window.renderMonthlyClose=async function(){const month=closeMonth.value||new Date().toISOString().slice(0,7);if(navigator.onLine)await pullInstitutionalClosings();const s=institutionalSnapshot(month),x=localClosings()[month]||{},status=x.status||'draft';const label={draft:'BROUILLON',prepared:'PRÉPARÉE — EN ATTENTE DU PRÉSIDENT',approved:'VALIDÉE & VERROUILLÉE',reopened:'RÉOUVERTE — À REPRÉPARER'}[status]||status;let actions='';if(role()==='treasurer'&&status!=='approved')actions=`<button class="quickBtn" onclick="prepareInstitutionalClose()">${status==='prepared'?'Repréparer la clôture':'Préparer la clôture'}</button>`;if(role()==='president'&&status==='prepared')actions='<button class="quickBtn" onclick="approveInstitutionalClose()">Valider la clôture</button>';if(role()==='president'&&status==='approved')actions='<button class="secondaryQuick" onclick="reopenInstitutionalClose()">Réouvrir avec motif</button>';const act=document.getElementById('monthlyCloseActions');if(act)act.innerHTML=actions;monthlyCloseBody.innerHTML=`<div class="profilePanel"><div class="closingStatus closing-${esc(status)}"><b>${esc(label)}</b></div><div class="memberStats"><div class="mini"><b>${money(s.due)}</b><span>Dû</span></div><div class="mini"><b>${money(s.paid)}</b><span>Payé</span></div><div class="mini"><b>${money(s.balance)}</b><span>Créances</span></div><div class="mini"><b>${money(s.cashIn)}</b><span>Entrées caisse</span></div><div class="mini"><b>${money(s.expenses)}</b><span>Dépenses</span></div><div class="mini"><b>${money(s.net)}</b><span>Solde net</span></div></div>${x.preparedAt?`<div class="small institutionalMeta">Préparée par Trésorier : ${new Date(x.preparedAt).toLocaleString('fr-FR')}</div>`:''}${x.approvedAt?`<div class="small institutionalMeta">Validée par Président : ${new Date(x.approvedAt).toLocaleString('fr-FR')}</div>`:''}${x.reopenedAt?`<div class="small institutionalMeta">Réouverte : ${new Date(x.reopenedAt).toLocaleString('fr-FR')} • Motif : ${esc(x.reopenedReason||'—')}</div>`:''}</div>`}
 window.saveMonthlyClose=function(){return role()==='treasurer'?prepareInstitutionalClose():role()==='president'?approveInstitutionalClose():alert('Accès réservé au Président et au Trésorier.')}
 window.reopenMonth=function(){return reopenInstitutionalClose()}

 async function registerChebselArchive(type,from,to,filename,metadata={}){if(!navigator.onLine||!responsible())return false;try{const {c,org,uid}=await context(),row={organization_id:org,archive_type:type,period_start:from||null,period_end:to||null,month_reference:(from||'').slice(0,7)||null,filename:String(filename||type),generated_by:uid,generated_role:role(),metadata};const q=await c.from('chebsel_archive_registry').insert(row);if(q.error)throw q.error;return true}catch(e){console.warn('Archive registry:',e);return false}}
 window.registerChebselArchive=registerChebselArchive;
 function wrapArchiveFunction(name,type,periodFn,fileFn){const base=window[name];if(typeof base!=='function')return;window[name]=async function(){const out=await base.apply(this,arguments);try{const p=periodFn(),fn=fileFn(p);await registerChebselArchive(type,p.from,p.to,fn,p.meta||{})}catch(e){console.warn('Archive hook '+name,e)}return out}}
 setTimeout(()=>{
  wrapArchiveFunction('saveReceiptJPEG','payment_receipt',()=>{const rows=[...document.querySelectorAll('#receiptPrint tr')].map(r=>[...r.cells].map(c=>c.textContent.trim()));const date=rows.find(x=>x[0]==='Date')?.[1]||new Date().toISOString().slice(0,10),no=document.querySelector('#receiptPrint .rmeta')?.textContent?.trim()||'REC';return {from:date,to:date,meta:{receipt:no}}},p=>`Recu_CHEBSEL_${p.meta.receipt}.jpg`);
  wrapArchiveFunction('saveTreasuryReportJPEG','financial_report',()=>{const r=treasuryReportData();return {from:r.from,to:r.to,meta:{totalIn:r.totalIn,totalOut:r.totalOut,net:r.net}}},p=>`Rapport_financier_CHEBSEL_${p.from}_${p.to}.jpg`);
  wrapArchiveFunction('savePunctualityReportJPEG','punctuality_report',()=>({from:document.getElementById('punctualityFrom').value,to:document.getElementById('punctualityTo').value,meta:{}}),p=>`Rapport_ponctualite_CHEBSEL_${p.from}_${p.to}.jpg`);
 },0);

 window.openArchives=async function(){if(!responsible()){alert('Accès réservé aux responsables.');return}document.getElementById('archivesView')?.classList.add('open');await renderArchives()};
 window.closeArchives=function(){document.getElementById('archivesView')?.classList.remove('open')};
 window.renderArchives=async function(){const box=document.getElementById('archiveList');if(!box)return;box.innerHTML='<div class="empty">Chargement…</div>';try{let rows=[];if(navigator.onLine){const {c,org}=await context(),q=await c.from('chebsel_archive_registry').select('*').eq('organization_id',org).order('generated_at',{ascending:false}).limit(300);if(q.error)throw q.error;rows=q.data||[];localStorage.setItem(ARCHIVE_CACHE_KEY,JSON.stringify(rows))}else rows=safeParse(ARCHIVE_CACHE_KEY)||[];const year=document.getElementById('archiveYear')?.value||'',type=document.getElementById('archiveType')?.value||'';rows=rows.filter(x=>(!year||String(x.period_start||x.generated_at).startsWith(year))&&(!type||x.archive_type===type));box.innerHTML=rows.length?rows.map(x=>`<div class="archiveRow"><div><b>${esc(({payment_receipt:'Reçu de paiement',financial_report:'Rapport financier',punctuality_report:'Rapport de ponctualité',monthly_closing_prepared:'Clôture préparée',monthly_closing_approved:'Clôture validée'})[x.archive_type]||x.archive_type)}</b><div class="memberMeta">${esc(x.period_start||'')} ${x.period_end&&x.period_end!==x.period_start?'→ '+esc(x.period_end):''} • ${esc(x.generated_role||'')} • ${new Date(x.generated_at).toLocaleString('fr-FR')}</div><div class="memberMeta">Fichier enregistré sur appareil : ${esc(x.filename)}</div></div></div>`).join(''):'<div class="empty">Aucune archive pour ce filtre.</div>'}catch(e){box.innerHTML='<div class="empty">Archives indisponibles : '+esc(e?.message||e)+'</div>'}}

 window.openConflictJournal=async function(){if(!responsible()){alert('Accès réservé aux responsables.');return}document.getElementById('conflictView')?.classList.add('open');await renderConflictJournal()};
 window.closeConflictJournal=function(){document.getElementById('conflictView')?.classList.remove('open')};
 window.renderConflictJournal=async function(){const box=document.getElementById('conflictList');if(!box)return;box.innerHTML='<div class="empty">Chargement…</div>';try{let rows=[];if(navigator.onLine){const {c,org}=await context(),q=await c.from('chebsel_conflict_log').select('*').eq('organization_id',org).order('occurred_at',{ascending:false}).limit(150);if(q.error)throw q.error;rows=q.data||[];localStorage.setItem(CONFLICT_CACHE_KEY,JSON.stringify(rows))}else rows=safeParse(CONFLICT_CACHE_KEY)||[];box.innerHTML=rows.length?rows.map(x=>`<div class="conflictRow"><div class="conflictHead"><b>${esc(x.domain==='attendance'?'Appel / Présence':'Finance')}</b><span>${new Date(x.occurred_at).toLocaleString('fr-FR')}</span></div><div class="memberMeta">Version retenue : ${esc(x.winning_role||'—')} (priorité ${Number(x.winning_priority||0)}) • Modification écartée : ${esc(x.losing_role||'—')} (priorité ${Number(x.losing_priority||0)})</div><div class="memberMeta">Élément : ${esc(x.entity_type||'')} ${x.entity_id?'• '+esc(x.entity_id):''}</div></div>`).join(''):'<div class="empty">Aucun conflit enregistré.</div>'}catch(e){box.innerHTML='<div class="empty">Journal indisponible : '+esc(e?.message||e)+'</div>'}}

 function readSet(){try{return new Set(JSON.parse(localStorage.getItem(ALERT_READ_KEY)||'[]'))}catch(e){return new Set()}}
 window.markAllAlertsRead=function(){const s=readSet();lastAlerts.forEach(a=>s.add(a.id));localStorage.setItem(ALERT_READ_KEY,JSON.stringify([...s].slice(-500)));renderAlertsPanel();updateAlertBadge()}
 function balance(e){return Math.max(0,Number(e.due||0)-Number(e.paid||0))}
 async function buildAlerts(){if(!responsible())return [];const list=[],f=safeParse(FIN_KEY)||{},entries=f.entries||[],members=centralMembers(),current=new Date().toISOString().slice(0,7),today=Date.now();const monthly=new Map();for(const e of entries){const b=balance(e);if(b<=0)continue;const m=members.find(x=>x.id===e.memberId),name=fullName(m);if(e.type==='monthly'&&String(e.date||'').slice(0,7)<current){const k=e.memberId,v=monthly.get(k)||{name,count:0,total:0};v.count++;v.total+=b;monthly.set(k,v)}const age=(today-new Date((e.date||current+'-01')+'T12:00:00').getTime())/86400000;if(age>30)list.push({id:`aged:${e.id}:${b}`,severity:age>90?'critical':'warn',title:'Dette ancienne',text:`${name} : ${money(b)} impayé depuis plus de ${Math.floor(age)} jours.`})}for(const [mid,x] of monthly)list.push({id:`monthly:${mid}:${x.count}:${x.total}`,severity:'warn',title:'Cotisation en retard',text:`${x.name} : ${x.count} mois en retard • ${money(x.total)}.`});const fines=entries.filter(e=>balance(e)>0&&(e.bridgeAuto||['lateness','absence','performance'].includes(e.type)));if(fines.length)list.push({id:`fines:${fines.length}:${fines.reduce((s,e)=>s+balance(e),0)}`,severity:'warn',title:'Amendes ouvertes',text:`${fines.length} amende(s) restent à payer pour ${money(fines.reduce((s,e)=>s+balance(e),0))}.`});const pm=prevMonth(),cl=localClosings()[pm];if(closingAllowed()&&cl?.status!=='approved'){list.push({id:`close:${pm}:${cl?.status||'none'}`,severity:cl?.status==='prepared'&&role()==='president'?'critical':'warn',title:'Clôture mensuelle',text:cl?.status==='prepared'?`${pm} est préparé et attend la validation du Président.`:`${pm} n’est pas encore validé.`})}const pending=Number(document.getElementById('syncPendingCount')?.textContent||0);if(pending>0)list.push({id:`sync-pending:${pending}`,severity:'warn',title:'Synchronisation en attente',text:`${pending} opération(s) attendent encore la synchronisation.`});const cs=String(document.getElementById('cloudState')?.textContent||'');if(/erreur|échec|failed|error/i.test(cs))list.push({id:`sync-error:${cs}`,severity:'critical',title:'Échec de synchronisation',text:cs});if(navigator.onLine){try{const {c,org}=await context(),q=await c.from('chebsel_conflict_log').select('id,domain,occurred_at').eq('organization_id',org).order('occurred_at',{ascending:false}).limit(20);if(!q.error&&(q.data||[]).length){const read=readSet(),fresh=(q.data||[]).filter(x=>!read.has('conflict:'+x.id));if(fresh.length)list.push({id:'conflict:'+fresh[0].id,severity:'info',title:'Conflit de synchronisation résolu',text:`${fresh.length} conflit(s) récent(s) ont été arbitrés selon les priorités CHEBSEL.`})}}catch(e){}}return list}
 async function updateAlertBadge(){lastAlerts=await buildAlerts();const read=readSet(),n=lastAlerts.filter(a=>!read.has(a.id)).length,b=document.getElementById('notificationBadge');if(b){b.textContent=n>99?'99+':String(n);b.style.display=n?'grid':'none'}return n}
 window.refreshInstitutionalAlerts=updateAlertBadge;
 window.openNotifications=async function(){if(!responsible())return;document.getElementById('notificationsView')?.classList.add('open');await renderAlertsPanel()};
 window.closeNotifications=function(){document.getElementById('notificationsView')?.classList.remove('open')};
 async function renderAlertsPanel(){lastAlerts=await buildAlerts();const read=readSet(),box=document.getElementById('notificationList');if(!box)return;box.innerHTML=lastAlerts.length?lastAlerts.map(a=>`<div class="alertRow alert-${esc(a.severity)} ${read.has(a.id)?'alert-read':''}"><div class="alertDot"></div><div><b>${esc(a.title)}</b><div class="memberMeta">${esc(a.text)}</div></div></div>`).join(''):'<div class="statusGood">✓ Aucun signal nécessitant votre attention.</div>';await updateAlertBadge()}
 window.renderAlertsPanel=renderAlertsPanel;

 if(typeof pullCloudFinance==='function'){const base=pullCloudFinance;window.pullCloudFinance=pullCloudFinance=async function(org){const out=await base.apply(this,arguments);await pullInstitutionalClosings();return out}}
 if(typeof refreshHome==='function'){const base=refreshHome;window.refreshHome=refreshHome=function(){const out=base.apply(this,arguments);setTimeout(()=>{applyInstitutionalRoleUI();updateAlertBadge()},0);return out}}
 function applyInstitutionalRoleUI(){const r=role(),bell=document.getElementById('notificationBtn'),arch=document.getElementById('archivesLaunchCard'),conf=document.getElementById('conflictsLaunchCard');if(bell)bell.style.display=responsible()?'grid':'none';if(arch)arch.classList.toggle('role-hidden',!responsible());if(conf)conf.classList.toggle('role-hidden',!responsible())}
 window.applyInstitutionalRoleUI=applyInstitutionalRoleUI;
 document.addEventListener('DOMContentLoaded',()=>{applyInstitutionalRoleUI();setTimeout(()=>{pullInstitutionalClosings();updateAlertBadge()},800)});
 window.addEventListener('online',()=>setTimeout(()=>{pullInstitutionalClosings();updateAlertBadge()},400));
 setInterval(()=>{if(responsible())updateAlertBadge()},60000);
})();
