import {setState} from './app-state.js';
import {loadSession,saveSession,clearSession} from './storage.js';
import {signInPassword,restoreCloudSession,cloudSignOut,getMyProfile,clearCloudSession} from './supabase-client.js';
let initialized=false;
const VALID_ROLES=new Set(['president','secretary','treasurer','visitor']);
const ROLE_EMAILS={president:'presidanchebsel@outlook.fr',secretary:'secretairechebsel@gmail.com',treasurer:'tresorierdugroupe@outlook.com'};
export async function restoreSession(){const local=loadSession();if(local?.role==='visitor'){setState({user:local.user||{name:'Visiteur'},role:'visitor'});return local}const cloud=await restoreCloudSession();if(cloud){try{const p=await getMyProfile();if(p?.active&&VALID_ROLES.has(String(p.role))){const session={role:String(p.role),user:{name:p.display_name||p.role,email:cloud.user?.email||''},cloud:true,organizationId:p.organization_id};saveSession(session);setState({user:session.user,role:session.role});return session}}catch(e){console.warn('Restore cloud profile',e)}}clearSession();clearCloudSession();setState({user:null,role:'visitor'});return null}
export async function signInRole(role,password=''){if(!VALID_ROLES.has(role))throw new Error('Rôle invalide');if(role==='visitor'){const session={role:'visitor',user:{name:'Visiteur'},cloud:false,createdAt:new Date().toISOString()};saveSession(session);setState({role:'visitor',user:session.user});return session}const email=ROLE_EMAILS[role];if(!email)throw new Error('Compte cloud non configuré');await signInPassword(email,password);const p=await getMyProfile();if(!p?.active||String(p.role)!==role){await cloudSignOut();throw new Error('Ce compte Supabase ne correspond pas au profil choisi.')}const session={role,user:{name:p.display_name||role,email},cloud:true,organizationId:p.organization_id,createdAt:new Date().toISOString()};saveSession(session);setState({role,user:session.user});return session}
export async function signOut(){try{await cloudSignOut()}catch{}clearSession();clearCloudSession();setState({user:null,role:'visitor'});location.reload()}
export async function initAuth(){if(initialized)return;initialized=true;await restoreSession()}
export {ROLE_EMAILS};
