import {AppState} from './app-state.js';
import {renderCurrent} from './router.js';
import {loadCommitteeCache,saveCommitteeCache} from './storage.js';
import {getMyProfile,restSelect,rpc} from './supabase-client.js';

const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const page=(t,s='')=>{const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',t));if(s)h.append(el('p','muted',s));w.append(h);return w};
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('fr-FR'):'—';
const isoToday=()=>new Date().toISOString().slice(0,10);
const plusTwoYears=date=>{if(!date)return'';const [y,m,d]=date.split('-').map(Number);return `${String(y+2).padStart(4,'0')}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');

async function loadCloud(){const p=await getMyProfile();if(!p?.organization_id)throw new Error('Organisation introuvable.');const org=encodeURIComponent(p.organization_id);const [mandates,audit]=await Promise.all([restSelect('committee_mandates',`select=*&organization_id=eq.${org}&order=start_date.desc`),restSelect('committee_audit_log',`select=*&organization_id=eq.${org}&order=created_at.desc&limit=100`)]);return saveCommitteeCache({mandates,audit})}

function currentCard(m){const box=el('section','panel');box.append(el('h3','',m?'Comité actuel':'Aucun comité actuel'));if(!m){box.append(el('p','muted','Aucun mandat actif.'));return box}const grid=el('div','monthly-kpis');for(const [label,value] of [['Président',m.president_name],['Secrétaire',m.secretary_name],['Trésorier',m.treasurer_name],['Début du mandat',fmt(m.start_date)],['Fin du mandat',fmt(m.expected_end_date)],['Durée','2 ans']]){const c=el('div','monthly-kpi');c.append(el('span','',label),el('b','',value||'—'));grid.append(c)}box.append(grid);return box}

function currentNamesForm(current,onSaved){const form=el('form','panel finance-form');form.innerHTML=`<h3>Noms du comité actuel</h3><p class="muted">Mandat fixe : ${fmt(current.start_date)} → ${fmt(current.expected_end_date)}. Saisissez ici les noms réels des trois titulaires. Cette opération ne crée pas un nouveau mandat.</p><div class="form-grid"><label>Président<input name="president" value="${esc(current.president_name)}" required autocomplete="off"></label><label>Secrétaire<input name="secretary" value="${esc(current.secretary_name)}" required autocomplete="off"></label><label>Trésorier<input name="treasurer" value="${esc(current.treasurer_name)}" required autocomplete="off"></label><label class="wide">Motif / référence<input name="reason" required value="Mise à jour des noms du comité actuel" autocomplete="off"></label><label class="wide">Observation<textarea name="notes"></textarea></label></div><label class="pin-toggle" style="margin-top:12px"><input name="transfer" type="checkbox"> Mettre aussi ces noms sur les profils d’accès Président / Secrétaire / Trésorier</label><p class="muted">Les mots de passe restent inchangés.</p><div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer les noms du comité actuel</button></div>`;
 form.onsubmit=async e=>{e.preventDefault();if(!navigator.onLine)return alert('Cette modification exige une connexion Internet.');const f=new FormData(form),president=String(f.get('president')||'').trim(),secretary=String(f.get('secretary')||'').trim(),treasurer=String(f.get('treasurer')||'').trim(),reason=String(f.get('reason')||'').trim();if(!president||!secretary||!treasurer||!reason)return;if(!confirm('Enregistrer ces noms pour le comité actuel 2026–2028 ?'))return;const b=form.querySelector('button[type="submit"]');b.disabled=true;try{await rpc('chebsel_update_current_committee_members',{p_president_name:president,p_secretary_name:secretary,p_treasurer_name:treasurer,p_reason:reason,p_notes:String(f.get('notes')||'').trim()||null,p_transfer_access:f.get('transfer')==='on'});alert('Noms du comité actuel enregistrés.');await onSaved()}catch(err){alert(`Modification impossible: ${err.message||err}`)}finally{b.disabled=false}};
 return form}

function replaceMemberForm(current,onSaved){const form=el('form','panel finance-form');form.innerHTML=`<h3>Changer un seul membre du comité</h3><p class="muted">Le mandat ${fmt(current.start_date)} → ${fmt(current.expected_end_date)} reste inchangé. Seul le titulaire choisi sera remplacé.</p><div class="form-grid"><label>Poste<select name="position"><option value="president">Président</option><option value="secretary">Secrétaire</option><option value="treasurer">Trésorier</option></select></label><label>Nouveau titulaire<input name="newName" required autocomplete="off"></label><label class="wide">Motif du remplacement<input name="reason" required placeholder="Démission, indisponibilité, décision du comité..."></label></div><label class="pin-toggle" style="margin-top:12px"><input name="transfer" type="checkbox"> Mettre aussi à jour le nom du profil d’accès correspondant</label><div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer le remplacement</button></div>`;
 form.onsubmit=async e=>{e.preventDefault();if(!navigator.onLine)return alert('Cette modification exige une connexion Internet.');const f=new FormData(form),position=String(f.get('position')||''),newName=String(f.get('newName')||'').trim(),reason=String(f.get('reason')||'').trim();if(!newName||!reason)return;if(!confirm('Confirmer le remplacement de ce membre du comité ?'))return;const b=form.querySelector('button[type="submit"]');b.disabled=true;try{await rpc('chebsel_replace_committee_member',{p_position:position,p_new_name:newName,p_reason:reason,p_transfer_access:f.get('transfer')==='on'});alert('Membre du comité remplacé.');await onSaved()}catch(err){alert(`Modification impossible: ${err.message||err}`)}finally{b.disabled=false}};
 return form}

function replaceWholeCommitteeForm(current,onSaved){const form=el('form','panel finance-form');const defaultStart=current?.expected_end_date||isoToday(),defaultEnd=plusTwoYears(defaultStart);form.innerHTML=`<h3>Changer tout le comité</h3><p class="muted">Cette opération clôture le mandat actuel et crée un nouveau mandat de 2 ans.</p><div class="form-grid"><label>Date de début<input name="start" type="date" value="${defaultStart}" required></label><label>Fin du mandat<input name="end" type="date" value="${defaultEnd}" required readonly></label><label>Président<input name="president" required autocomplete="off"></label><label>Secrétaire<input name="secretary" required autocomplete="off"></label><label>Trésorier<input name="treasurer" required autocomplete="off"></label><label class="wide">Motif du changement<input name="reason" required placeholder="Élection, fin de mandat, renouvellement général..."></label><label class="wide">Observation<textarea name="notes"></textarea></label></div><label class="pin-toggle" style="margin-top:12px"><input name="transfer" type="checkbox"> Mettre à jour les noms associés aux trois profils d’accès</label><p class="muted">Les mots de passe ne sont pas modifiés automatiquement.</p><div class="dialog-actions"><button class="btn primary" type="submit">Activer le nouveau comité</button></div>`;
 const start=form.elements.start,end=form.elements.end;start.addEventListener('change',()=>{end.value=plusTwoYears(start.value)});
 form.onsubmit=async e=>{e.preventDefault();if(!navigator.onLine)return alert('Le changement complet du comité exige une connexion Internet.');const f=new FormData(form);if(!confirm('Confirmer le remplacement complet du comité ? Le mandat actuel passera dans l’historique.'))return;const b=form.querySelector('button[type="submit"]');b.disabled=true;try{await rpc('chebsel_change_committee',{p_start_date:String(f.get('start')),p_expected_end_date:String(f.get('end')),p_president_name:String(f.get('president')||'').trim(),p_secretary_name:String(f.get('secretary')||'').trim(),p_treasurer_name:String(f.get('treasurer')||'').trim(),p_change_reason:String(f.get('reason')||'').trim(),p_notes:String(f.get('notes')||'').trim()||null,p_transfer_access:f.get('transfer')==='on'});alert('Nouveau comité activé pour un mandat de 2 ans.');await onSaved()}catch(err){alert(`Changement impossible: ${err.message||err}`)}finally{b.disabled=false}};
 return form}

function historyBlock(rows){const box=el('section','panel');box.append(el('h3','','Historique des mandats'));if(!rows.length){box.append(el('p','muted','Aucun ancien mandat.'));return box}const list=el('div','finance-list');for(const m of rows){const r=el('article','finance-row'),left=el('div');left.append(el('strong','',`${fmt(m.start_date)} → ${fmt(m.effective_end_date||m.expected_end_date)}`),el('span','muted',`Président: ${m.president_name} • Secrétaire: ${m.secretary_name} • Trésorier: ${m.treasurer_name}`));r.append(left,el('span','muted','Ancien'));list.append(r)}box.append(list);return box}

function auditBlock(rows){const box=el('section','panel');box.append(el('h3','','Journal d’audit'));if(!rows.length){box.append(el('p','muted','Aucune trace enregistrée.'));return box}const list=el('div','finance-list');for(const a of rows.slice(0,30)){const d=a.details||{},r=el('div','finance-row'),left=el('div');let title='Changement de comité',desc=d.reason||'';if(a.action==='committee_member_replaced'){title=`Remplacement — ${d.position||'membre'}`;desc=`${d.old_name||'—'} → ${d.new_name||'—'}${d.reason?' • '+d.reason:''}`}else if(a.action==='current_committee_members_updated'||a.action==='committee_members_updated'){title='Mise à jour des noms du comité actuel'}else if(a.action==='committee_replaced'||a.action==='committee_changed'){title='Remplacement complet du comité'}left.append(el('strong','',title),el('span','muted',`${new Date(a.created_at).toLocaleString('fr-FR')}${desc?' • '+desc:''}`));r.append(left);list.append(r)}box.append(list);return box}

export async function renderCommittee(){const w=page('Gestion du Comité','Mandat de 2 ans, noms des titulaires, remplacement individuel ou renouvellement complet.');w.dataset.renderLock='true';if(AppState.role!=='president'){w.append(el('div','panel','Cette section est réservée au Président.'));return w}let cache=loadCommitteeCache();if(navigator.onLine){try{cache=await loadCloud()}catch(e){w.append(el('div','panel',`Cloud indisponible : ${e.message||e}. Affichage du dernier cache local.`))}}else w.append(el('div','panel','Mode hors ligne : consultation uniquement. Les changements de comité exigent Internet.'));const refreshOnce=async()=>{await loadCloud();await renderCurrent({force:true})};const current=(cache.mandates||[]).find(x=>x.status==='current')||null,former=(cache.mandates||[]).filter(x=>x.status!=='current');w.append(currentCard(current));if(navigator.onLine&&current)w.append(currentNamesForm(current,refreshOnce),replaceMemberForm(current,refreshOnce),replaceWholeCommitteeForm(current,refreshOnce));w.append(historyBlock(former),auditBlock(cache.audit||[]));return w}
