import {AppState} from './app-state.js';
import {saveAppSettings} from './storage.js';
import {getMyProfile,restSelect,rpc} from './supabase-client.js';
const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const page=(t,s='')=>{const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',t));if(s)h.append(el('p','muted',s));w.append(h);return w};
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('fr-FR'):'—';
function cacheData(mandates,audit){const current=AppState.data.settings||{},committeeCache={mandates:Array.isArray(mandates)?mandates:[],audit:Array.isArray(audit)?audit:[],cachedAt:new Date().toISOString()};const next=saveAppSettings({committeeCache});AppState.data.settings=next;return committeeCache}
async function loadCloud(){const p=await getMyProfile();if(!p?.organization_id)throw new Error('Organisation introuvable.');const org=encodeURIComponent(p.organization_id),mandates=await restSelect('committee_mandates',`select=*&organization_id=eq.${org}&order=start_date.desc`),audit=await restSelect('committee_audit_log',`select=*&organization_id=eq.${org}&order=created_at.desc&limit=100`);return cacheData(mandates,audit)}
function currentCard(m){const box=el('section','panel');box.append(el('h3','',m?'Comité actuel':'Aucun comité actuel'));if(!m){box.append(el('p','muted','Enregistrez le premier mandat du comité.'));return box}const grid=el('div','monthly-kpis');for(const [label,value] of [['Président',m.president_name],['Secrétaire',m.secretary_name],['Trésorier',m.treasurer_name],['Début',fmt(m.start_date)],['Fin prévue',fmt(m.expected_end_date)],['Accès transférés',m.access_transferred?'Oui':'Non']]){const c=el('div','monthly-kpi');c.append(el('span','',label),el('b','',value||'—'));grid.append(c)}box.append(grid);if(m.change_reason)box.append(el('p','muted',`Motif : ${m.change_reason}`));return box}
function historyBlock(rows){const box=el('section','panel');box.append(el('h3','','Historique des comités'));if(!rows.length){box.append(el('p','muted','Aucun ancien mandat.'));return box}const list=el('div','finance-list');for(const m of rows){const r=el('article','finance-row'),left=el('div');left.append(el('strong','',`${fmt(m.start_date)} → ${fmt(m.effective_end_date||m.expected_end_date)}`),el('span','muted',`Président: ${m.president_name} • Secrétaire: ${m.secretary_name} • Trésorier: ${m.treasurer_name}`));r.append(left,el('span','muted',m.status==='former'?'Ancien':'Actuel'));list.append(r)}box.append(list);return box}
function auditBlock(rows){const box=el('section','panel');box.append(el('h3','','Journal d’audit'));if(!rows.length){box.append(el('p','muted','Aucune trace enregistrée.'));return box}const list=el('div','finance-list');for(const a of rows.slice(0,20)){const r=el('div','finance-row'),d=a.details||{},left=el('div');left.append(el('strong','',a.action==='committee_changed'?'Changement de comité':a.action),el('span','muted',`${new Date(a.created_at).toLocaleString('fr-FR')} • ${d.reason||''}`));r.append(left);list.append(r)}box.append(list);return box}
function changeForm(onSaved){const form=el('form','panel finance-form');form.innerHTML=`<h3>Nouveau mandat</h3><p class="muted">L’ancien comité restera dans l’historique. Le nouveau mandat deviendra le comité actuel.</p><div class="form-grid"><label>Date de début<input name="start" type="date" required></label><label>Fin prévue<input name="end" type="date"></label><label>Président<input name="president" required></label><label>Secrétaire<input name="secretary" required></label><label>Trésorier<input name="treasurer" required></label><label class="wide">Motif du changement<input name="reason" required placeholder="Élection, fin de mandat, remplacement..."></label><label class="wide">Observation<textarea name="notes"></textarea></label></div><label class="pin-toggle" style="margin-top:12px"><input name="transfer" type="checkbox"> Transférer aussi l’identité des accès Président / Secrétaire / Trésorier aux nouveaux titulaires</label><p class="muted">Le transfert met à jour les noms associés aux comptes de rôle existants. Il n’efface aucun historique et ne change pas automatiquement les mots de passe.</p><div class="dialog-actions"><button class="btn primary" type="submit">Activer le nouveau comité</button></div>`;
 form.onsubmit=async e=>{e.preventDefault();if(!navigator.onLine)return alert('Le changement de comité exige une connexion Internet afin de garantir la cohérence entre tous les appareils.');const f=new FormData(form);if(!confirm('Confirmer le changement de comité ? Cette action sera inscrite dans le journal d’audit.'))return;const b=form.querySelector('button[type="submit"]');b.disabled=true;try{await rpc('chebsel_change_committee',{p_start_date:String(f.get('start')),p_expected_end_date:String(f.get('end')||'')||null,p_president_name:String(f.get('president')||'').trim(),p_secretary_name:String(f.get('secretary')||'').trim(),p_treasurer_name:String(f.get('treasurer')||'').trim(),p_change_reason:String(f.get('reason')||'').trim(),p_notes:String(f.get('notes')||'').trim()||null,p_transfer_access:f.get('transfer')==='on'});alert('Nouveau comité activé.');await onSaved()}catch(err){alert(`Changement impossible: ${err.message||err}`)}finally{b.disabled=false}};return form}
export async function renderCommittee(){const w=page('Gestion du Comité','Mandats, historique et transfert contrôlé des accès.');if(AppState.role!=='president'){w.append(el('div','panel','Cette section est réservée au Président.'));return w}let cache=AppState.data.settings?.committeeCache||{mandates:[],audit:[]};if(navigator.onLine){try{cache=await loadCloud()}catch(e){w.append(el('div','panel',`Cloud indisponible : ${e.message||e}. Affichage du dernier cache local.`))}}else{w.append(el('div','panel','Mode hors ligne : consultation du dernier état synchronisé. Les changements de comité sont désactivés.'))}const redraw=async()=>{await loadCloud();window.CHEBSEL?.rerender?.()};const current=(cache.mandates||[]).find(x=>x.status==='current')||null,former=(cache.mandates||[]).filter(x=>x.status!=='current');w.append(currentCard(current));if(navigator.onLine)w.append(changeForm(redraw));w.append(historyBlock(former),auditBlock(cache.audit||[]));return w}
