import {AppState,updateState} from './app-state.js';
const LIVE={members:'chebsel_master_members_v1',attendance:'chebsel_attendance_app_v1',finance:'chebsel_finance_app_v1'};
const KEYS={members:'chebsel_v2_preview_members',attendance:'chebsel_v2_preview_attendance',finance:'chebsel_v2_preview_finance',session:'chebsel_v2_preview_session',settings:'chebsel_v2_preview_settings',seeded:'chebsel_v2_preview_seeded'};
function parse(key,fallback){try{const raw=localStorage.getItem(key);if(raw==null)return fallback;const v=JSON.parse(raw);return v??fallback}catch{return fallback}}
export function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
export function readAttendanceEnvelope(){const v=parse(KEYS.attendance,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function seedFromV1Once(){if(localStorage.getItem(KEYS.seeded)==='1')return;const a=parse(LIVE.attendance,{}),f=parse(LIVE.finance,{});let members=parse(LIVE.members,null);if(!Array.isArray(members)||!members.length){if(Array.isArray(a?.members)&&a.members.length)members=a.members;else if(Array.isArray(f?.members))members=f.members;else members=[]}save(KEYS.members,members);save(KEYS.attendance,a||{});save(KEYS.finance,f||{});localStorage.setItem(KEYS.seeded,'1')}
export function loadLocalData(){seedFromV1Once();const attendanceRaw=readAttendanceEnvelope(),financeRaw=parse(KEYS.finance,{}),members=parse(KEYS.members,[]),settings=parse(KEYS.settings,{});updateState('data',{members:Array.isArray(members)?members:[],attendance:Array.isArray(attendanceRaw?.calls)?attendanceRaw.calls:[],finance:Array.isArray(financeRaw?.entries)?financeRaw.entries:[],settings});return AppState.data}
export function saveMembersCompatible(list){save(KEYS.members,list);const a=readAttendanceEnvelope();save(KEYS.attendance,{...a,members:list.map(x=>({...x}))});const f=parse(KEYS.finance,{});save(KEYS.finance,{...f,members:list.map(x=>({...x}))})}
export function saveAttendanceCompatible(calls,settingsPatch=null){const current=readAttendanceEnvelope(),next={...current,members:(AppState.data.members||current.members||[]).map(m=>({...m})),calls:Array.isArray(calls)?calls:[]};if(settingsPatch&&typeof settingsPatch==='object')next.settings={...(current.settings||{}),...settingsPatch};save(KEYS.attendance,next);return next}
export function resetPreviewFromV1(){localStorage.removeItem(KEYS.seeded);seedFromV1Once();return loadLocalData()}
export function loadSession(){return parse(KEYS.session,null)}export function saveSession(session){save(KEYS.session,session)}export function clearSession(){localStorage.removeItem(KEYS.session)}export {KEYS};
