import {AppState,updateState} from './app-state.js';
const LIVE={members:'chebsel_master_members_v1',attendance:'chebsel_attendance_app_v1',finance:'chebsel_finance_app_v1'};const KEYS={members:'chebsel_v2_preview_members',attendance:'chebsel_v2_preview_attendance',finance:'chebsel_v2_preview_finance',session:'chebsel_v2_preview_session',settings:'chebsel_v2_preview_settings',conflicts:'chebsel_v2_preview_conflicts',notificationRead:'chebsel_v2_preview_notification_read',seeded:'chebsel_v2_preview_seeded'};
function parse(key,fallback){try{const raw=localStorage.getItem(key);if(raw==null)return fallback;const v=JSON.parse(raw);return v??fallback}catch{return fallback}}function changed(){window.dispatchEvent(new Event('chebsel:data-changed'))}export function save(key,value){localStorage.setItem(key,JSON.stringify(value))}export function readRaw(key,fallback={}){return parse(key,fallback)}
function seedFromV1Once(){if(localStorage.getItem(KEYS.seeded)==='1')return;const a=parse(LIVE.attendance,{}),f=parse(LIVE.finance,{});let members=parse(LIVE.members,null);if(!Array.isArray(members)||!members.length){if(Array.isArray(a?.members)&&a.members.length)members=a.members;else if(Array.isArray(f?.members))members=f.members;else members=[]}save(KEYS.members,members);save(KEYS.attendance,a||{});save(KEYS.finance,f||{});save(KEYS.settings,{});save(KEYS.conflicts,[]);localStorage.setItem(KEYS.seeded,'1')}
export function readAttendanceEnvelope(){const v=parse(KEYS.attendance,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}export function readFinanceEnvelope(){const v=parse(KEYS.finance,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
export function loadLocalData(){seedFromV1Once();const a=readAttendanceEnvelope(),f=readFinanceEnvelope(),members=parse(KEYS.members,[]),settings=parse(KEYS.settings,{}),conflicts=parse(KEYS.conflicts,[]);updateState('data',{members:Array.isArray(members)?members:[],attendance:Array.isArray(a.calls)?a.calls:[],finance:Array.isArray(f.entries)?f.entries:[],expenses:Array.isArray(f.expenses)?f.expenses:[],financeSettings:f.settings&&typeof f.settings==='object'?f.settings:{},settings:settings&&typeof settings==='object'?settings:{},conflicts:Array.isArray(conflicts)?conflicts:[]});return AppState.data}
export function saveMembersCompatible(list){save(KEYS.members,list);const a=readAttendanceEnvelope();save(KEYS.attendance,{...a,members:list.map(x=>({...x}))});const f=readFinanceEnvelope();save(KEYS.finance,{...f,members:list.map(x=>({...x}))});changed()}
export function saveAttendanceCompatible(calls,settingsPatch=null){const a=readAttendanceEnvelope(),next={...a,members:(AppState.data.members||[]).map(x=>({...x})),calls:Array.isArray(calls)?calls:[]};if(settingsPatch)next.settings={...(a.settings||{}),...settingsPatch};save(KEYS.attendance,next);changed();return next}
export function saveFinanceCompatible({entries,expenses,settings}={}){const f=readFinanceEnvelope(),next={...f,members:(AppState.data.members||[]).map(x=>({...x})),entries:Array.isArray(entries)?entries:(f.entries||[]),expenses:Array.isArray(expenses)?expenses:(f.expenses||[]),settings:settings?{...(f.settings||{}),...settings}:(f.settings||{})};save(KEYS.finance,next);changed();return next}
export function saveAppSettings(settings){const next={...(parse(KEYS.settings,{})||{}),...(settings||{})};save(KEYS.settings,next);updateState('data',{...AppState.data,settings:next});changed();return next}export function saveConflicts(conflicts){const list=Array.isArray(conflicts)?conflicts:[];save(KEYS.conflicts,list);updateState('data',{...AppState.data,conflicts:list});changed();return list}
export function makeBackupBundle(){return {schema:'CHEBSEL_V2_BACKUP',preview:true,createdAt:new Date().toISOString(),members:parse(KEYS.members,[]),attendance:readAttendanceEnvelope(),finance:readFinanceEnvelope(),settings:parse(KEYS.settings,{}),conflicts:parse(KEYS.conflicts,[])}}export function restoreBackupBundle(b){if(!b||b.schema!=='CHEBSEL_V2_BACKUP'||!Array.isArray(b.members))throw new Error('Fichier de sauvegarde CHEBSEL v2 invalide.');save(KEYS.members,b.members);save(KEYS.attendance,b.attendance||{});save(KEYS.finance,b.finance||{});save(KEYS.settings,b.settings||{});save(KEYS.conflicts,Array.isArray(b.conflicts)?b.conflicts:[]);const data=loadLocalData();changed();return data}
export function resetPreviewFromV1(){localStorage.removeItem(KEYS.seeded);seedFromV1Once();const data=loadLocalData();changed();return data}export function loadSession(){return parse(KEYS.session,null)}export function saveSession(session){save(KEYS.session,session)}export function clearSession(){localStorage.removeItem(KEYS.session)}export {KEYS};
