import {APP_VERSION,AppState,setState,updateState,subscribe} from './app-state.js';
import {initRouter,registerRoute,navigate,resetTo,renderCurrent,back} from './router.js';
import {getRoleConfig} from './role-config.js';
import {loadLocalData} from './storage.js';
import {initAuth,signIn,signOut} from './auth.js';
import {initUpdates} from './updates.js';
import {registerMemberRoutes} from './members.js';
import {initNotifications,refreshNotifications,renderNotificationsPage} from './notifications.js';
let initialized=false;const $=(s,r=document)=>r.querySelector(s);function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n}function card(route,icon,label){const b=el('button','menu-card');b.type='button';b.dataset.route=route;b.append(el('span','menu-icon',icon),el('span','menu-label',label));b.addEventListener('click',()=>navigate(route));return b}function page(title,subtitle=''){const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',title));if(subtitle)h.append(el('p','muted',subtitle));w.append(h);return w}function home(){const cfg=getRoleConfig(AppState.role),w=page(cfg.label,'CHEBSEL v2 Clean Core'),g=el('div','menu-grid');cfg.menus.forEach(([r,i,l])=>g.append(card(r,i,l)));w.append(g);return w}function hub(t,items){const w=page(t),g=el('div','menu-grid');items.forEach(x=>g.append(card(...x)));w.append(g);return w}const lazy=(file,name)=>async()=>{const m=await import(file);return m[name]()};
function registerCoreRoutes(){registerRoute('home',home);registerMemberRoutes(registerRoute);registerRoute('secretariat',()=>hub('Secrétariat',[['attendance','✅','Appel'],['attendance-settings','⚙️','Paramètres'],['attendance-history','📈','Historique']]));registerRoute('attendance',lazy('./attendance.js','renderAttendancePage'));registerRoute('attendance-settings',lazy('./attendance.js','renderAttendanceSettings'));registerRoute('attendance-history',lazy('./attendance.js','renderAttendanceHistory'));registerRoute('punctuality-reports',lazy('./attendance.js','renderAttendanceHistory'));registerRoute('treasury',()=>hub('Trésorerie',[['payments','💰','Paiements'],['debtors','📋','Débiteurs'],['expenses','💸','Dépenses'],['finance-history','📈','Historique'],['finance-reports','📊','Rapports financiers']]));registerRoute('payments',()=>hub('Paiements',[['payment-entry','💵','Saisir'],['finance-settings','⚙️','Paramètres']]));registerRoute('payment-entry',lazy('./finance.js','renderPaymentEntry'));registerRoute('finance-settings',lazy('./finance.js','renderFinanceSettings'));registerRoute('debtors',lazy('./finance.js','renderDebtors'));registerRoute('expenses',lazy('./finance.js','renderExpenses'));registerRoute('finance-history',lazy('./finance.js','renderFinanceHistory'));registerRoute('finance-reports',lazy('./finance.js','renderFinanceReports'));registerRoute('reports',lazy('./admin.js','renderReports'));registerRoute('archives',lazy('./admin.js','renderArchives'));registerRoute('conflicts',lazy('./admin.js','renderConflicts'));registerRoute('settings',lazy('./admin.js','renderSettings'));registerRoute('privacy',lazy('./admin.js','renderPrivacy'));registerRoute('about',lazy('./admin.js','renderAbout'));registerRoute('notifications',renderNotificationsPage)}
function renderHeader(){$('#versionChip').textContent=`v${APP_VERSION}`;$('#roleLabel').textContent=getRoleConfig(AppState.role).label;$('#userLabel').textContent=AppState.user?.name||'Mode visiteur';const backBtn=$('#globalBackBtn');if(backBtn)backBtn.disabled=AppState.navigationStack.length<=1;const bell=$('#notificationBtn');if(bell){bell.classList.toggle('has-unread',AppState.notifications.unread>0);let badge=bell.querySelector('.notification-badge');if(AppState.notifications.unread>0){if(!badge){badge=el('span','notification-badge');bell.append(badge)}badge.textContent=String(AppState.notifications.unread)}else badge?.remove()}}
function applyBootSettings(){const theme=AppState.data.settings?.theme||'dark';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme==='light'?'light':'dark'}function showRolePicker(){const modal=$('#rolePicker');if(!modal)return;modal.hidden=false;modal.querySelectorAll('[data-role]').forEach(btn=>btn.onclick=()=>{const role=btn.dataset.role;signIn({role,user:{name:btn.dataset.name||getRoleConfig(role).label}});refreshNotifications();modal.hidden=true;resetTo('home');renderHeader()})}async function startBackgroundServices(){window.addEventListener('online',()=>updateState('syncStatus',{online:true}),{passive:true});window.addEventListener('offline',()=>updateState('syncStatus',{online:false}),{passive:true});window.addEventListener('chebsel:data-changed',refreshNotifications,{passive:true});try{await initUpdates()}catch(e){console.warn('Update manager',e)}}
export async function initApp(){if(initialized)return;initialized=true;const splash=$('#splash');try{initAuth();loadLocalData();applyBootSettings();initRouter();registerCoreRoutes();initNotifications();subscribe(renderHeader);$('#notificationBtn')?.addEventListener('click',()=>navigate('notifications'));renderHeader();void renderCurrent();if(!AppState.user)showRolePicker();setState({boot:{ready:true,error:null}});requestAnimationFrame(()=>{document.body.classList.add('app-ready');if(splash)splash.hidden=true});void startBackgroundServices()}catch(error){console.error(error);setState({boot:{ready:false,error:String(error?.message||error)}});if(splash)splash.innerHTML='<div class="splash-card"><h1>CHEBSEL</h1><p>Erreur de démarrage.</p></div>'}}
window.CHEBSEL={navigate,back,signOut,state:AppState,rerender:renderCurrent,resetHome:()=>resetTo('home'),refreshNotifications};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initApp,{once:true});else initApp();
