import {AppState,updateState} from './app-state.js';
import {navigate} from './router.js';
import {saveAttendanceCompatible,readAttendanceEnvelope} from './storage.js';

const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
const norm=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const uid=()=>globalThis.crypto?.randomUUID?.()||`call_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const fullName=m=>[m?.first,m?.last].filter(Boolean).join(' ').trim()||m?.name||'Sans nom';
const today=()=>new Date().toISOString().slice(0,10);
const DEFAULT_ACTIVITIES=['Répétition','Prestation 2e dimanche EBSEL','Concert','Réunion','Formation','Culte','Veillée','Autre'];

export const STATUS={
 '':{label:'— Non marqué —',kind:'none'},P:{label:'Présent',kind:'present'},RM:{label:'Retard motivé',kind:'late'},RNM:{label:'Retard non motivé',kind:'late'},AM:{label:'Absence motivée',kind:'absent'},ANM:{label:'Absence non motivée',kind:'absent'},ANMP:{label:'Absence non motivée — prestation',kind:'absent'}
};
export function normalizeAttendanceStatus(raw,isPerformance=false){const s=String(raw||'').trim().toUpperCase();if(['P','PRESENT','PRÉSENT'].includes(s))return'P';if(['RM','RETARD MOTIVE','RETARD MOTIVÉ','R','RETARD EXCUSE','RETARD EXCUSÉ'].includes(s))return'RM';if(['RNM','RETARD NON MOTIVE','RETARD NON MOTIVÉ'].includes(s))return'RNM';if(['AM','ABSENCE MOTIVEE','ABSENCE MOTIVÉE','A','ABSENCE EXCUSEE','ABSENCE EXCUSÉE'].includes(s))return'AM';if(['ANMP','ANM PRESTATION','ABSENCE NON MOTIVEE PRESTATION','ABSENCE NON MOTIVÉE PRESTATION'].includes(s))return'ANMP';if(['ANM','ABSENCE NON MOTIVEE','ABSENCE NON MOTIVÉE'].includes(s))return isPerformance?'ANMP':'ANM';return STATUS[s]?s:''}
function canEdit(){return ['president','secretary'].includes(AppState.role)}
function activeMembers(){return (AppState.data.members||[]).filter(m=>m?.active!==false).sort((a,b)=>fullName(a).localeCompare(fullName(b),'fr'))}
function calls(){return Array.isArray(AppState.data.attendance)?AppState.data.attendance:[]}
function settings(){return readAttendanceEnvelope().settings||{}}
function activityTypes(){const custom=settings().activityTypes;return Array.isArray(custom)&&custom.length?[...new Set(custom.filter(Boolean))]:DEFAULT_ACTIVITIES}
function isPerformance(call){const s=norm(`${call?.activityType||call?.activity||''}`);return s.includes('prestation')||s.includes('concert')}
function selectedCall(){const id=AppState.ui?.selectedAttendanceCallId;return calls().find(c=>String(c?.id)===String(id))||null}
function pageHead(title,subtitle){const h=el('div','page-head split-head'),copy=el('div');copy.append(el('h1','',title),el('p','muted',subtitle));h.append(copy);return h}
function field(label,input){const w=el('label','form-field');w.append(el('span','',label),input);return w}
function input(type,name,value=''){const x=document.createElement('input');x.type=type;x.name=name;x.value=value||'';return x}
function select(name,options,value=''){const x=document.createElement('select');x.name=name;for(const [v,l] of options){const o=document.createElement('option');o.value=v;o.textContent=l;x.append(o)}x.value=value||'';return x}
function minutesBetween(start,arrival){if(!start||!arrival)return 0;const [sh,sm]=start.split(':').map(Number),[ah,am]=arrival.split(':').map(Number);if([sh,sm,ah,am].some(Number.isNaN))return 0;return Math.max(0,(ah*60+am)-(sh*60+sm))}
function callStats(call){let present=0,late=0,absent=0,total=0,lateMinutes=0;for(const r of Object.values(call?.records||{})){const s=normalizeAttendanceStatus(r?.status,isPerformance(call));if(!s)continue;total++;if(s==='P')present++;else if(['RM','RNM'].includes(s)){late++;lateMinutes+=Number(r?.minutesLate||0)}else if(['AM','ANM','ANMP'].includes(s))absent++}return{present,late,absent,total,lateMinutes,avgLate:late?Math.round(lateMinutes/late):0,rate:total?Math.round(((present+late)/total)*100):0,punctualityRate:total?Math.round(present/total*100):0}}

export function renderAttendancePage(){
 const existing=selectedCall(),cfg=settings(),editable=canEdit(),w=el('section','page');const head=pageHead(existing?'Modifier l’appel':'Fiche d’Appel','Présence et ponctualité — CHEBSEL v2');const actions=el('div','member-actions');const hist=el('button','btn secondary','Historique / Ponctualité');hist.onclick=()=>navigate('attendance-history');actions.append(hist);if(editable){const par=el('button','btn secondary','Paramètres');par.onclick=()=>navigate('attendance-settings');actions.append(par)}head.append(actions);w.append(head);
 const meta=el('div','panel attendance-meta');const date=input('date','date',existing?.date||today());const activity=select('activityType',activityTypes().map(x=>[x,x]),existing?.activityType||existing?.activity||cfg.defaultActivity||activityTypes()[0]);const startTime=input('time','startTime',existing?.startTime||cfg.defaultStartTime||'18:00');const note=input('text','note',existing?.note||existing?.notes||'');note.placeholder='Observation générale facultative';meta.append(field('Date',date),field("Type d’activité",activity),field("Heure de l’activité",startTime),field('Observation',note));w.append(meta);
 const summary=el('div','attendance-live-summary');w.append(summary);const list=el('div','attendance-list');w.append(list);const records={};const performance=()=>isPerformance({activityType:activity.value});
 for(const m of activeMembers()){
  const old=existing?.records?.[m.id]||{},row=el('article','attendance-row attendance-row-time');const who=el('div','attendance-person');who.append(el('strong','',fullName(m)),el('span','muted',`N° ${m.no||'—'}`));const st=select('status',Object.entries(STATUS).map(([k,v])=>[k,v.label]),normalizeAttendanceStatus(old.status,isPerformance(existing)));const arrival=input('time','arrivalTime',old.arrivalTime||old.arrival||'');const mins=input('number','minutesLate',String(old.minutesLate??minutesBetween(existing?.startTime,old.arrivalTime||old.arrival)));mins.min='0';mins.readOnly=true;mins.tabIndex=-1;const obs=input('text','memberNote',old.note||old.reason||old.observation||'');obs.placeholder='Motif / observation';
  const recalc=()=>{const n=minutesBetween(startTime.value,arrival.value);mins.value=String(n);if(n>0&&st.value==='P')st.value='RM';if(n===0&&['RM','RNM'].includes(st.value)&&arrival.value)st.value='P';updateLive()};arrival.addEventListener('change',recalc);startTime.addEventListener('change',recalc);st.addEventListener('change',()=>{if(st.value==='ANM'&&performance())st.value='ANMP';if(st.value==='ANMP'&&!performance())st.value='ANM';updateLive()});if(!editable){st.disabled=true;arrival.disabled=true;obs.disabled=true}records[m.id]={statusEl:st,arrivalEl:arrival,minutesEl:mins,noteEl:obs};row.append(who,st,arrival,mins,obs);list.append(row);
 }
 function updateLive(){let p=0,l=0,a=0,u=0,totalMin=0;for(const r of Object.values(records)){const s=normalizeAttendanceStatus(r.statusEl.value,performance());if(s==='P')p++;else if(['RM','RNM'].includes(s)){l++;totalMin+=Number(r.minutesEl.value||0)}else if(['AM','ANM','ANMP'].includes(s))a++;else u++}summary.textContent=`Présents ${p} • Retards ${l} (${totalMin} min) • Absents ${a} • Non marqués ${u}`}
 list.addEventListener('change',updateLive);updateLive();
 if(editable){const bar=el('div','sticky-save-bar'),save=el('button','btn primary',existing?'Enregistrer les modifications':'Enregistrer l’appel');save.onclick=()=>{if(!date.value)return alert('Chwazi dat aktivite a.');const rec={};for(const[mid,r]of Object.entries(records)){const s=normalizeAttendanceStatus(r.statusEl.value,performance());if(!s)continue;rec[mid]={...(existing?.records?.[mid]||{}),status:s,arrivalTime:r.arrivalEl.value||'',minutesLate:Number(r.minutesEl.value||0),note:r.noteEl.value.trim()}}const now=new Date().toISOString(),call={...(existing||{}),id:existing?.id||uid(),date:date.value,activityType:activity.value,activity:activity.value,startTime:startTime.value,note:note.value.trim(),records:rec,createdAt:existing?.createdAt||now,updatedAt:now};const next=[...calls()],i=next.findIndex(c=>String(c?.id)===String(call.id));if(i>=0)next[i]=call;else next.push(call);saveAttendanceCompatible(next);updateState('data',{...AppState.data,attendance:next});updateState('ui',{...(AppState.ui||{}),selectedAttendanceCallId:call.id});window.CHEBSEL?.refreshNotifications?.();save.textContent='Enregistré ✓'};const fresh=el('button','btn secondary','Nouvel appel');fresh.onclick=()=>{updateState('ui',{...(AppState.ui||{}),selectedAttendanceCallId:null});window.CHEBSEL?.rerender?.()};bar.append(save,fresh);w.append(bar)}return w;
}

function monthHealth(rows){const by=new Map();for(const c of rows){const m=String(c.date||'').slice(0,7);if(!m)continue;const s=callStats(c),v=by.get(m)||{month:m,total:0,present:0,late:0,absent:0,lateMinutes:0};v.total+=s.total;v.present+=s.present;v.late+=s.late;v.absent+=s.absent;v.lateMinutes+=s.lateMinutes;by.set(m,v)}return [...by.values()].sort((a,b)=>a.month.localeCompare(b.month)).slice(-6).map(v=>({...v,punctuality:v.total?Math.round(v.present/v.total*100):0,attendance:v.total?Math.round((v.present+v.late)/v.total*100):0,avgLate:v.late?Math.round(v.lateMinutes/v.late):0}))}
export function renderAttendanceHistory(){
 const w=el('section','page');w.append(pageHead('Historique & santé de la ponctualité','Résumé chiffré et évolution du groupe sur les 6 derniers mois.'));const tools=el('div','panel member-toolbar'),q=input('search','q',''),month=input('month','month','');q.placeholder='Rechercher activité ou date…';tools.append(q,month);w.append(tools);const health=el('div','panel punctuality-health'),summary=el('div','attendance-live-summary'),list=el('div','attendance-history-list');w.append(health,summary,list);
 const render=()=>{const needle=norm(q.value),mo=month.value,all=[...calls()],rows=all.filter(c=>(!mo||String(c.date||'').startsWith(mo))&&(!needle||norm(`${c.date} ${c.activityType||c.activity}`).includes(needle))).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));let P=0,L=0,A=0,T=0,M=0;for(const c of rows){const s=callStats(c);P+=s.present;L+=s.late;A+=s.absent;T+=s.total;M+=s.lateMinutes}const punctual=T?Math.round(P/T*100):0,avg=L?Math.round(M/L):0;summary.textContent=`${rows.length} appel(s) • Présents ${P} • Retards ${L} • Absents ${A} • Ponctualité ${punctual}% • Retard moyen ${avg} min`;
  health.replaceChildren();const kpis=el('div','member-stats');[['Ponctualité',`${punctual}%`],['Présences',String(P)],['Retards',String(L)],['Absences',String(A)],['Retard moyen',`${avg} min`]].forEach(([k,v])=>{const x=el('div','member-stat');x.append(el('b','',v),el('span','',k));kpis.append(x)});health.append(kpis);const months=monthHealth(all),chart=el('div','health-chart');for(const m of months){const col=el('div','health-col');const bar=el('div','health-bar');bar.style.height=`${Math.max(4,m.punctuality)}%`;bar.title=`${m.month}: ${m.punctuality}% ponctualité`;col.append(el('b','',`${m.punctuality}%`),bar,el('span','',m.month.slice(5)));chart.append(col)}health.append(chart);
  list.replaceChildren();if(!rows.length)return list.append(el('div','panel empty-state','Aucun appel trouvé.'));for(const c of rows){const s=callStats(c),row=el('article','panel history-call'),copy=el('div');copy.append(el('h3','',c.activityType||c.activity||'Activité'),el('p','muted',`${c.date||'—'} • ${c.startTime||'—'} • Ponctualité ${s.punctualityRate}% • Retard moyen ${s.avgLate} min • P ${s.present} / R ${s.late} / A ${s.absent}`));const open=el('button','btn secondary',canEdit()?'Ouvrir / modifier':'Consulter');open.onclick=()=>{updateState('ui',{...(AppState.ui||{}),selectedAttendanceCallId:c.id});navigate('attendance')};row.append(copy,open);list.append(row)}};q.oninput=render;month.onchange=render;render();return w;
}

export function renderAttendanceSettings(){if(!canEdit()){const w=el('section','page');w.append(el('div','panel','Accès réservé au Président et au Secrétaire.'));return w}const cfg=settings(),w=el('section','page');w.append(pageHead("Paramètres de l’appel","Types d’activité et heure par défaut."));const form=el('div','panel settings-form'),activity=select('defaultActivity',activityTypes().map(x=>[x,x]),cfg.defaultActivity||activityTypes()[0]),time=input('time','defaultStartTime',cfg.defaultStartTime||'18:00');form.append(field('Type d’activité par défaut',activity),field("Heure de l’activité par défaut",time));const types=el('div','panel');types.append(el('h3','',"Types d’activité"));const list=el('div','member-actions');const renderTypes=()=>{list.replaceChildren(...activityTypes().map(x=>el('span','status-badge is-active',x)))};renderTypes();const add=input('text','newActivity','');add.placeholder='Ajouter un type d’activité';const addBtn=el('button','btn secondary','Ajouter');addBtn.onclick=()=>{const v=add.value.trim();if(!v)return;const arr=[...new Set([...activityTypes(),v])];saveAttendanceCompatible(calls(),{...settings(),activityTypes:arr});add.value='';window.CHEBSEL?.rerender?.()};types.append(list,add,addBtn);const save=el('button','btn primary','Enregistrer les paramètres');save.onclick=()=>{saveAttendanceCompatible(calls(),{...settings(),defaultActivity:activity.value,defaultStartTime:time.value});save.textContent='Enregistré ✓'};w.append(form,types,save);return w}
export function registerAttendanceRoutes(registerRoute){registerRoute('attendance',renderAttendancePage);registerRoute('attendance-settings',renderAttendanceSettings);registerRoute('attendance-history',renderAttendanceHistory);registerRoute('punctuality-reports',renderAttendanceHistory)}
