import {setState} from './app-state.js';
import {loadSession,saveSession,clearSession} from './storage.js';
import {signInPassword,restoreCloudSession,cloudSignOut,getMyProfile,clearCloudSession} from './supabase-client.js';
let initialized=false;
const VALID_ROLES=new Set(['president','secretary','treasurer','visitor']);
const ROLE_EMAILS={president:'presidanchebsel@outlook.fr',secretary:'secretairechebsel@gmail.com',treasurer:'tresorierdugroupe@outlook.com'};
const OFFLINE_KEY=location.pathname.includes('/v2-preview/')?'chebsel_v2_preview_offline_auth':'chebsel_v2_offline_auth';
const enc=new TextEncoder();
function readOffline(){try{return JSON.parse(localStorage.getItem(OFFLINE_KEY)||'{}')||{}}catch{return {}}}
function bytesToB64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function b64ToBytes(s){const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function derive(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(String(password)),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:210000},key,256);return new Uint8Array(bits)}
async function rememberOffline(role,password,profile,email){const salt=crypto.getRandomValues(new Uint8Array(16)),hash=await derive(password,salt),all=readOffline();all[role]={salt:bytesToB64(salt),hash:bytesToB64(hash),displayName:profile.display_name||role,email,organizationId:profile.organization_id,verifiedAt:new Date().toISOString()};localStorage.setItem(OFFLINE_KEY,JSON.stringify(all))}
async function verifyOffline(role,password){const cfg=readOffline()[role];if(!cfg?.salt||!cfg?.hash)return null;const got=await derive(password,b64ToBytes(cfg.salt)),expected=b64ToBytes(cfg.hash);if(got.length!==expected.length)return null;let diff=0;for(let i=0;i<got.length;i++)diff|=got[i]^expected[i];return diff===0?cfg:null}
export function hasOfflineAccess(role){const c=readOffline()[role];return !!(c?.salt&&c?.hash)}
export async function restoreSession(){const local=loadSession();if(local?.role==='visitor'){setState({user:local.user||{name:'Visiteur'},role:'visitor'});return local}if(!navigator.onLine&&local?.role&&VALID_ROLES.has(local.role)&&hasOfflineAccess(local.role)){const session={...local,cloud:false,offline:true};setState({user:session.user||{name:readOffline()[local.role]?.displayName||local.role},role:local.role});return session}const cloud=await restoreCloudSession();if(cloud){try{const p=await getMyProfile();if(p?.active&&VALID_ROLES.has(String(p.role))){const session={role:String(p.role),user:{name:p.display_name||p.role,email:cloud.user?.email||''},cloud:true,offline:false,organizationId:p.organization_id};saveSession(session);setState({user:session.user,role:session.role});return session}}catch(e){console.warn('Restore cloud profile',e)}}clearSession();clearCloudSession();setState({user:null,role:'visitor'});return null}
export async function signInRole(role,password=''){if(!VALID_ROLES.has(role))throw new Error('Rôle invalide');if(role==='visitor'){const session={role:'visitor',user:{name:'Visiteur'},cloud:false,createdAt:new Date().toISOString()};saveSession(session);setState({role:'visitor',user:session.user});return session}const email=ROLE_EMAILS[role];if(!email)throw new Error('Compte cloud non configuré');if(!navigator.onLine){const cfg=await verifyOffline(role,password);if(!cfg)throw new Error(hasOfflineAccess(role)?'Mot de passe hors ligne incorrect.':'Ce profil doit se connecter au moins une fois avec Internet sur cet appareil avant de pouvoir être utilisé hors ligne.');const session={role,user:{name:cfg.displayName||role,email:cfg.email||email},cloud:false,offline:true,organizationId:cfg.organizationId,createdAt:new Date().toISOString()};saveSession(session);setState({role,user:session.user});return session}await signInPassword(email,password);const p=await getMyProfile();if(!p?.active||String(p.role)!==role){await cloudSignOut();throw new Error('Ce compte Supabase ne correspond pas au profil choisi.')}await rememberOffline(role,password,p,email);const session={role,user:{name:p.display_name||role,email},cloud:true,offline:false,organizationId:p.organization_id,createdAt:new Date().toISOString()};saveSession(session);setState({role,user:session.user});return session}
export async function signOut(){try{if(navigator.onLine)await cloudSignOut()}catch{}clearSession();clearCloudSession();setState({user:null,role:'visitor'});location.reload()}
export async function initAuth(){if(initialized)return;initialized=true;await restoreSession()}
export {ROLE_EMAILS};
