import {AppState,updateState} from './app-state.js';
import {saveFinanceCompatible} from './storage.js';

const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const uid=()=>crypto?.randomUUID?.()||`f_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const money=v=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0))+' G';
const nameOf=id=>{const m=(AppState.data.members||[]).find(x=>String(x.id)===String(id));return m?[m.first,m.last].filter(Boolean).join(' '):'Membre inconnu'};
const canWrite=()=>['president','treasurer'].includes(AppState.role);
const entries=()=>Array.isArray(AppState.data.finance)?AppState.data.finance:[];
const expenses=()=>Array.isArray(AppState.data.expenses)?AppState.data.expenses:[];
const DEFAULT_TYPES=[
 {id:'monthly',label:'Cotisation mensuelle',amount:125,kind:'contribution'},
 {id:'rnm',label:'Retard non motivé',amount:25,kind:'fine'},
 {id:'anm',label:'Absence non motivée',amount:50,kind:'fine'},
 {id:'anmp',label:'Absence non motivée — prestation',amount:250,kind:'fine'},
 {id:'special',label:'Cotisation spéciale',amount:0,kind:'contribution'},
 {id:'other',label:'Autre',amount:0,kind:'other'}
];
function types(){const s=AppState.data.financeSettings||{},custom=Array.isArray(s.paymentTypes)?s.paymentTypes:[];const base=DEFAULT_TYPES.map(x=>({...x}));if(Number.isFinite(Number(s.monthlyContribution)))base.find(x=>x.id==='monthly').amount=Number(s.monthlyContribution);if(Number.isFinite(Number(s.lateFine)))base.find(x=>x.id==='rnm').amount=Number(s.lateFine);if(Number.isFinite(Number(s.absenceFine)))base.find(x=>x.id==='anm').amount=Number(s.absenceFine);if(Number.isFinite(Number(s.performanceAbsenceFine)))base.find(x=>x.id==='anmp').amount=Number(s.performanceAbsenceFine);for(const c of custom){const i=base.findIndex(x=>x.id===c.id);if(i>=0)base[i]={...base[i],...c};else base.push(c)}return base}
function persist({entries:es=entries(),expenses:xs=expenses(),financeSettings=AppState.data.financeSettings||{}}={}){saveFinanceCompatible({entries:es,expenses:xs,settings:financeSettings});updateState('data',{...AppState.data,finance:es,expenses:xs,financeSettings});window.CHEBSEL?.refreshNotifications?.()}
function validEntry(e){return !e?.voided&&!e?.cancelled&&e?.status!=='cancelled'}
function validExpense(x){return !x?.deletedAt&&!x?.cancelled&&x?.status!=='cancelled'}
function memberBalance(id){let due=0,paid=0;for(const e of entries().filter(x=>String(x.memberId??x.member_id)==String(id)&&validEntry(x))){due+=Number(e.due??e.amountDue??0)||0;paid+=Number(e.paid??e.amountPaid??0)||0}return{due,paid,balance:Math.max(0,due-paid)}}
function page(title,sub=''){const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',title));if(sub)h.append(el('p','muted',sub));w.append(h);return w}
function btn(text,fn,primary=false){const b=el('button',`btn ${primary?'primary':'secondary'}`,text);b.type='button';b.onclick=fn;return b}
function today(){return new Date().toISOString().slice(0,10)}
function monthStart(){return `${today().slice(0,7)}-01`}

export function renderPaymentEntry(){
 const w=page('Saisir un paiement','Le type sélectionné charge automatiquement le montant correspondant.');if(!canWrite()){w.append(el('div','panel','Lecture seule.'));return w}
 const form=el('form','panel finance-form'),members=(AppState.data.members||[]).filter(m=>m.active!==false&&!m.deletedAt).sort((a,b)=>nameOf(a.id).localeCompare(nameOf(b.id),'fr')),opts=types();
 form.innerHTML=`<div class="form-grid"><label>Membre<select name="memberId" required><option value="">Choisir…</option>${members.map(m=>`<option value="${m.id}">${nameOf(m.id)}</option>`).join('')}</select></label><label>Date<input name="date" type="date" value="${today()}" required></label><label>Type de paiement<select name="paymentType" required>${opts.map(x=>`<option value="${x.id}">${x.label} — ${money(x.amount)}</option>`).join('')}</select></label><label>Montant dû<input name="due" type="number" min="0" step="1"></label><label>Montant payé<input name="paid" type="number" min="0" step="1" value="0"></label><label>Dette actuelle<input name="currentDebt" readonly></label><label>Dette après paiement<input name="projectedDebt" readonly></label><label class="wide">Observation<textarea name="note"></textarea></label></div><div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer</button></div>`;
 const member=form.elements.memberId,type=form.elements.paymentType,due=form.elements.due,paid=form.elements.paid,current=form.elements.currentDebt,projected=form.elements.projectedDebt;
 const recalc=()=>{const bal=member.value?memberBalance(member.value).balance:0;current.value=money(bal);projected.value=money(Math.max(0,bal+Number(due.value||0)-Number(paid.value||0)))};
 const applyType=()=>{const t=opts.find(x=>x.id===type.value)||opts[0];due.value=String(Number(t?.amount||0));recalc()};
 member.onchange=recalc;type.onchange=applyType;due.oninput=recalc;paid.oninput=recalc;applyType();
 form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),mid=String(fd.get('memberId')||''),t=opts.find(x=>x.id===String(fd.get('paymentType')));if(!mid)return;const before=memberBalance(mid).balance,item={id:uid(),memberId:mid,date:String(fd.get('date')||''),type:t?.kind||'other',paymentTypeId:t?.id||'other',typeLabel:t?.label||'Autre',due:Number(fd.get('due')||0),paid:Number(fd.get('paid')||0),debtBefore:before,debtAfter:Math.max(0,before+Number(fd.get('due')||0)-Number(fd.get('paid')||0)),note:String(fd.get('note')||'').trim(),createdAt:new Date().toISOString(),source:'v2',localDirty:true};persist({entries:[...entries(),item]});if(item.paid>0)window.dispatchEvent(new CustomEvent('chebsel:payment-recorded',{detail:{entry:item}}));alert(`Paiement enregistré. Dette restante: ${money(item.debtAfter)}`);form.reset();form.elements.date.value=today();applyType()};
 w.append(form);return w
}

export function renderFinanceSettings(){
 const w=page('Paramètres financiers','Montants standards et types de paiement personnalisés.');const s={monthlyContribution:125,lateFine:25,absenceFine:50,performanceAbsenceFine:250,paymentTypes:[],...(AppState.data.financeSettings||{})};
 const box=el('form','panel finance-form');box.innerHTML=`<div class="form-grid"><label>Cotisation mensuelle<input name="monthlyContribution" type="number" min="0" value="${s.monthlyContribution}"></label><label>RNM — Retard non motivé<input name="lateFine" type="number" min="0" value="${s.lateFine}"></label><label>ANM — Absence non motivée<input name="absenceFine" type="number" min="0" value="${s.absenceFine}"></label><label>ANMP — Absence prestation<input name="performanceAbsenceFine" type="number" min="0" value="${s.performanceAbsenceFine}"></label></div>${canWrite()?'<div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer les montants</button></div>':''}`;
 if(canWrite())box.onsubmit=e=>{e.preventDefault();const fd=new FormData(box);persist({financeSettings:{...s,monthlyContribution:Number(fd.get('monthlyContribution')||0),lateFine:Number(fd.get('lateFine')||0),absenceFine:Number(fd.get('absenceFine')||0),performanceAbsenceFine:Number(fd.get('performanceAbsenceFine')||0)}});window.CHEBSEL?.rerender?.()};else box.querySelectorAll('input').forEach(i=>i.disabled=true);w.append(box);
 const custom=el('div','panel');custom.append(el('h3','',"Types de paiement / cotisation"));const list=el('div','finance-list');const draw=()=>{list.replaceChildren(...types().map(t=>{const r=el('div','finance-row'),left=el('div');left.append(el('strong','',t.label),el('span','muted',`${money(t.amount)} • ${t.kind}`));r.append(left);if(canWrite()&&!DEFAULT_TYPES.some(d=>d.id===t.id)){r.append(btn('Retirer',()=>{const next=(AppState.data.financeSettings?.paymentTypes||[]).filter(x=>x.id!==t.id);persist({financeSettings:{...(AppState.data.financeSettings||{}),paymentTypes:next}});window.CHEBSEL?.rerender?.()}))}return r}))};draw();
 if(canWrite()){const add=el('form','form-grid');add.innerHTML='<label>Nom du nouvo type<input name="label" placeholder="Ex. Uniforme"></label><label>Montant<input name="amount" type="number" min="0" value="0"></label><label>Catégorie<select name="kind"><option value="contribution">Cotisation</option><option value="fine">Amende</option><option value="other">Autre</option></select></label><div class="wide dialog-actions"><button class="btn secondary">Ajouter le type</button></div>';add.onsubmit=e=>{e.preventDefault();const fd=new FormData(add),label=String(fd.get('label')||'').trim();if(!label)return;const next=[...(AppState.data.financeSettings?.paymentTypes||[]),{id:`custom_${Date.now().toString(36)}`,label,amount:Number(fd.get('amount')||0),kind:String(fd.get('kind')||'other')}];persist({financeSettings:{...(AppState.data.financeSettings||{}),paymentTypes:next}});window.CHEBSEL?.rerender?.()};custom.append(list,add)}else custom.append(list);w.append(custom);return w
}

export function renderDebtors(){const w=page('Débiteurs','Dette cumulée calculée automatiquement à partir du dû et du payé.');const q=el('input','finance-search');q.type='search';q.placeholder='Rechercher un membre…';const list=el('div','debtor-list');w.append(q,list);const render=()=>{const s=q.value.toLowerCase().trim(),rows=(AppState.data.members||[]).filter(m=>!m.deletedAt).map(m=>({m,b:memberBalance(m.id)})).filter(x=>x.b.balance>0&&(!s||nameOf(x.m.id).toLowerCase().includes(s))).sort((a,b)=>b.b.balance-a.b.balance);list.replaceChildren(...(rows.length?rows.map(({m,b})=>{const c=el('div','panel debtor-row'),x=el('div');x.append(el('strong','',nameOf(m.id)),el('div','muted',`Dû ${money(b.due)} • Payé ${money(b.paid)}`));c.append(x,el('b','debt-amount',money(b.balance)));return c}):[el('div','panel empty-state','Aucun débiteur.')]))};q.oninput=render;render();return w}

export function renderExpenses(){
 const w=page('Dépenses','Enregistrer et suivre les sorties de caisse sans supprimer la traçabilité.');
 const active=()=>expenses().filter(validExpense).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));
 if(canWrite()){
  const form=el('form','panel finance-form expense-entry-form');form.innerHTML=`<div class="form-grid"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Montant<input name="amount" type="number" min="1" step="1" required></label><label>Catégorie<input name="category" placeholder="Ex. Transport, uniforme, matériel"></label><label>Référence<input name="reference" placeholder="Facture, reçu, bon..."></label><label class="wide">Motif<input name="reason" required placeholder="Motif de la dépense"></label><label class="wide">Notes<textarea name="notes" placeholder="Observation facultative"></textarea></label></div><div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer la dépense</button></div>`;
  form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),amount=Number(fd.get('amount')||0),reason=String(fd.get('reason')||'').trim(),date=String(fd.get('date')||'');if(!date)return alert('Indiquez la date de la dépense.');if(!(amount>0))return alert('Indiquez un montant supérieur à zéro.');if(!reason)return alert('Indiquez le motif de la dépense.');const x={id:uid(),date,amount,category:String(fd.get('category')||'').trim(),reference:String(fd.get('reference')||'').trim(),reason,notes:String(fd.get('notes')||'').trim(),createdAt:new Date().toISOString(),createdBy:AppState.user?.name||'',deletedAt:null};persist({expenses:[...expenses(),x]});window.CHEBSEL?.rerender?.()};w.append(form)
 }
 const summary=el('div','attendance-live-summary'),list=el('div','finance-list');const rows=active();summary.textContent=`${rows.length} dépense(s) • Total : ${money(rows.reduce((s,x)=>s+Number(x.amount||0),0))}`;
 if(!rows.length)list.append(el('div','panel empty-state','Aucune dépense enregistrée.'));else for(const x of rows){const c=el('article','panel expense-card'),left=el('div','expense-copy');left.append(el('strong','',x.reason||x.label||'Dépense'),el('div','muted',`${x.date||'—'}${x.category?' • '+x.category:''}${x.reference?' • Réf. '+x.reference:''}`));if(x.notes||x.note)left.append(el('div','muted',x.notes||x.note));const right=el('div','expense-actions');right.append(el('b','debt-amount',money(x.amount)));if(canWrite())right.append(btn('Annuler',()=>{if(!confirm('Annuler cette dépense ? Elle restera traçable.'))return;const next=expenses().map(r=>r.id===x.id?{...r,deletedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:r);persist({expenses:next});window.CHEBSEL?.rerender?.()}));c.append(left,right);list.append(c)}
 w.append(summary,list);return w
}

export function renderFinanceHistory(){return page('Historique / Histogramme','Cette route est rendue par le dashboard historique dédié.')}

function reportData(from,to){const a=from<=to?from:to,z=from<=to?to:from;const income=entries().filter(e=>validEntry(e)&&String(e.date||'')>=a&&String(e.date||'')<=z&&Number(e.paid??e.amountPaid??0)>0).map(e=>({date:String(e.date||''),source:nameOf(e.memberId??e.member_id),reference:e.reference||e.ref||e.id||'',label:e.typeLabel||e.label||'Paiement',amount:Number(e.paid??e.amountPaid??0)})).sort((x,y)=>x.date.localeCompare(y.date));const outs=expenses().filter(x=>validExpense(x)&&String(x.date||'')>=a&&String(x.date||'')<=z).sort((x,y)=>String(x.date||'').localeCompare(String(y.date||'')));const totalIn=income.reduce((s,x)=>s+x.amount,0),totalOut=outs.reduce((s,x)=>s+Number(x.amount||0),0);return{from:a,to:z,income,expenses:outs,totalIn,totalOut,net:totalIn-totalOut}}
function csvDownload(r){const lines=[['RAPPORT FINANCIER CHEBSEL'],['Période',r.from,r.to],[],['SYNTHÈSE'],['Entrées',r.totalIn],['Dépenses',r.totalOut],['Solde net',r.net],[],['ENTRÉES'],['Date','Source','Type','Référence','Montant'],...r.income.map(x=>[x.date,x.source,x.label,x.reference,x.amount]),[],['DÉPENSES'],['Date','Motif','Catégorie','Référence','Montant'],...r.expenses.map(x=>[x.date,x.reason||x.label||'Dépense',x.category||'',x.reference||'',x.amount])];const csv='\ufeff'+lines.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Rapport_financier_CHEBSEL_${r.from}_${r.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
function printReport(container){const win=window.open('','_blank');if(!win)return;win.document.write(`<html><head><title>Rapport financier CHEBSEL</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#111}table{width:100%;border-collapse:collapse;margin:12px 0 24px}th,td{border:1px solid #bbb;padding:8px;text-align:left}.report-summary{display:flex;gap:20px}.report-summary div{border:1px solid #bbb;padding:12px}</style></head><body>${container.outerHTML}</body></html>`);win.document.close();win.focus();win.print()}

export function renderFinanceReports(){
 const w=page('Rapport financier','Rapport détaillé par période avec entrées, dépenses et solde net.');const controls=el('div','panel report-controls');controls.innerHTML=`<label>Du <input name="from" type="date" value="${monthStart()}"></label><label>Au <input name="to" type="date" value="${today()}"></label><button class="btn primary" data-generate type="button">Générer</button><button class="btn secondary" data-csv type="button" disabled>Exporter CSV</button><button class="btn secondary" data-print type="button" disabled>Imprimer</button>`;const out=el('div','finance-report');let current=null;const render=()=>{const from=controls.querySelector('[name="from"]').value,to=controls.querySelector('[name="to"]').value;if(!from||!to)return;current=reportData(from,to);out.replaceChildren();const report=el('section','panel finance-report-document');report.innerHTML=`<div class="report-title"><h2>Rapport financier CHEBSEL</h2><p>Période : ${current.from} au ${current.to}</p></div><div class="report-summary"><div><b>${money(current.totalIn)}</b><span>Entrées</span></div><div><b>${money(current.totalOut)}</b><span>Dépenses</span></div><div><b>${money(current.net)}</b><span>Solde net</span></div></div><h3>Entrées</h3><div class="table-wrap"><table class="finance-report-table"><thead><tr><th>Date</th><th>Source</th><th>Type</th><th>Référence</th><th>Montant</th></tr></thead><tbody>${current.income.length?current.income.map(x=>`<tr><td>${x.date}</td><td>${x.source}</td><td>${x.label}</td><td>${x.reference||'—'}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5">Aucune entrée.</td></tr>'}</tbody></table></div><h3>Dépenses</h3><div class="table-wrap"><table class="finance-report-table"><thead><tr><th>Date</th><th>Motif</th><th>Catégorie</th><th>Référence</th><th>Montant</th></tr></thead><tbody>${current.expenses.length?current.expenses.map(x=>`<tr><td>${x.date||'—'}</td><td>${x.reason||x.label||'Dépense'}</td><td>${x.category||'—'}</td><td>${x.reference||'—'}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5">Aucune dépense.</td></tr>'}</tbody></table></div>`;out.append(report);controls.querySelector('[data-csv]').disabled=false;controls.querySelector('[data-print]').disabled=false};controls.querySelector('[data-generate]').onclick=render;controls.querySelector('[data-csv]').onclick=()=>current&&csvDownload(current);controls.querySelector('[data-print]').onclick=()=>{const node=out.querySelector('.finance-report-document');if(node)printReport(node)};w.append(controls,out);render();return w
}

export function registerFinanceRoutes(registerRoute){registerRoute('payment-entry',renderPaymentEntry);registerRoute('finance-settings',renderFinanceSettings);registerRoute('debtors',renderDebtors);registerRoute('expenses',renderExpenses);registerRoute('finance-history',renderFinanceHistory);registerRoute('finance-reports',renderFinanceReports)}
