import {AppState,updateState} from './app-state.js';
import {readRaw,KEYS,saveFinanceCompatible} from './storage.js';

const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const uid=()=>crypto?.randomUUID?.()||`f_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const money=v=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0))+' G';
const nameOf=id=>{const m=(AppState.data.members||[]).find(x=>String(x.id)===String(id));return m?[m.first,m.last].filter(Boolean).join(' '):'Membre inconnu'};
const canWrite=()=>['president','treasurer'].includes(AppState.role);
const monthNow=()=>new Date().toISOString().slice(0,7);
const entries=()=>Array.isArray(AppState.data.finance)?AppState.data.finance:[];
const expenses=()=>Array.isArray(AppState.data.expenses)?AppState.data.expenses:[];
const DEFAULT_TYPES=[
 {id:'monthly',label:'Cotisation mensuelle',amount:125,kind:'contribution'},
 {id:'rnm',label:'Retard non motivé',amount:25,kind:'fine'},
 {id:'anm',label:'Absence non motivée',amount:50,kind:'fine'},
 {id:'anmp',label:'Absence non motivée — prestation',amount:250,kind:'fine'},
 {id:'special',label:'Cotisation spéciale',amount:0,kind:'contribution'},
 {id:'other',label:'Autre',amount:0,kind:'other'}
];
function types(){const s=AppState.data.financeSettings||{},custom=Array.isArray(s.paymentTypes)?s.paymentTypes:[];const base=DEFAULT_TYPES.map(x=>({...x}));if(Number.isFinite(Number(s.monthlyContribution)))base.find(x=>x.id==='monthly').amount=Number(s.monthlyContribution);if(Number.isFinite(Number(s.lateFine)))base.find(x=>x.id==='rnm').amount=Number(s.lateFine);if(Number.isFinite(Number(s.absenceFine)))base.find(x=>x.id==='anm').amount=Number(s.absenceFine);if(Number.isFinite(Number(s.performanceAbsenceFine)))base.find(x=>x.id==='anmp').amount=Number(s.performanceAbsenceFine);for(const c of custom){const i=base.findIndex(x=>x.id===c.id);if(i>=0)base[i]={...base[i],...c};else base.push(c)}return base}
function persist({entries:es=entries(),expenses:xs=expenses(),financeSettings=AppState.data.financeSettings||{}}={}){saveFinanceCompatible({entries:es,expenses:xs,settings:financeSettings});updateState('data',{...AppState.data,finance:es,expenses:xs,financeSettings});window.CHEBSEL?.refreshNotifications?.()}
function memberBalance(id){let due=0,paid=0;for(const e of entries().filter(x=>String(x.memberId??x.member_id)==String(id))){if(e.voided||e.cancelled||e.status==='cancelled')continue;due+=Number(e.due??e.amountDue??0)||0;paid+=Number(e.paid??e.amountPaid??0)||0}return{due,paid,balance:Math.max(0,due-paid)}}
function page(title,sub=''){const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',title));if(sub)h.append(el('p','muted',sub));w.append(h);return w}
function btn(text,fn,primary=false){const b=el('button',`btn ${primary?'primary':'secondary'}`,text);b.type='button';b.onclick=fn;return b}

export function renderPaymentEntry(){
 const w=page('Saisir un paiement','Le type sélectionné charge automatiquement le montant correspondant.');if(!canWrite()){w.append(el('div','panel','Lecture seule.'));return w}
 const form=el('form','panel finance-form'),members=(AppState.data.members||[]).filter(m=>m.active!==false).sort((a,b)=>nameOf(a.id).localeCompare(nameOf(b.id),'fr')),opts=types();
 form.innerHTML=`<div class="form-grid"><label>Membre<select name="memberId" required><option value="">Choisir…</option>${members.map(m=>`<option value="${m.id}">${nameOf(m.id)}</option>`).join('')}</select></label><label>Date<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Type de paiement<select name="paymentType" required>${opts.map(x=>`<option value="${x.id}">${x.label} — ${money(x.amount)}</option>`).join('')}</select></label><label>Montant dû<input name="due" type="number" min="0" step="1"></label><label>Montant payé<input name="paid" type="number" min="0" step="1" value="0"></label><label>Dette actuelle<input name="currentDebt" readonly></label><label>Dette après paiement<input name="projectedDebt" readonly></label><label class="wide">Observation<textarea name="note"></textarea></label></div><div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer</button></div>`;
 const member=form.elements.memberId,type=form.elements.paymentType,due=form.elements.due,paid=form.elements.paid,current=form.elements.currentDebt,projected=form.elements.projectedDebt;
 const applyType=()=>{const t=opts.find(x=>x.id===type.value)||opts[0];due.value=String(Number(t?.amount||0));recalc()};
 const recalc=()=>{const bal=member.value?memberBalance(member.value).balance:0;current.value=money(bal);projected.value=money(Math.max(0,bal+Number(due.value||0)-Number(paid.value||0)))};
 member.onchange=recalc;type.onchange=applyType;due.oninput=recalc;paid.oninput=recalc;applyType();
 form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),mid=String(fd.get('memberId')||''),t=opts.find(x=>x.id===String(fd.get('paymentType')));if(!mid)return;const item={id:uid(),memberId:mid,date:String(fd.get('date')||''),type:t?.kind||'other',paymentTypeId:t?.id||'other',typeLabel:t?.label||'Autre',due:Number(fd.get('due')||0),paid:Number(fd.get('paid')||0),note:String(fd.get('note')||'').trim(),createdAt:new Date().toISOString(),source:'v2'};persist({entries:[...entries(),item]});alert(`Paiement enregistré. Dette restante: ${money(memberBalance(mid).balance)}`);form.reset();form.elements.date.value=new Date().toISOString().slice(0,10);applyType()};
 w.append(form);return w
}

export function renderFinanceSettings(){
 const w=page('Paramètres financiers','Montants standards et types de paiement personnalisés.');const s={monthlyContribution:125,lateFine:25,absenceFine:50,performanceAbsenceFine:250,paymentTypes:[],...(AppState.data.financeSettings||{})};
 const box=el('form','panel finance-form');box.innerHTML=`<div class="form-grid"><label>Cotisation mensuelle<input name="monthlyContribution" type="number" min="0" value="${s.monthlyContribution}"></label><label>RNM — Retard non motivé<input name="lateFine" type="number" min="0" value="${s.lateFine}"></label><label>ANM — Absence non motivée<input name="absenceFine" type="number" min="0" value="${s.absenceFine}"></label><label>ANMP — Absence prestation<input name="performanceAbsenceFine" type="number" min="0" value="${s.performanceAbsenceFine}"></label></div>${canWrite()?'<div class="dialog-actions"><button class="btn primary" type="submit">Enregistrer les montants</button></div>':''}`;
 if(canWrite())box.onsubmit=e=>{e.preventDefault();const fd=new FormData(box);persist({financeSettings:{...s,monthlyContribution:Number(fd.get('monthlyContribution')||0),lateFine:Number(fd.get('lateFine')||0),absenceFine:Number(fd.get('absenceFine')||0),performanceAbsenceFine:Number(fd.get('performanceAbsenceFine')||0)}});window.CHEBSEL?.rerender?.()};else box.querySelectorAll('input').forEach(i=>i.disabled=true);w.append(box);
 const custom=el('div','panel');custom.append(el('h3','',"Types de paiement / cotisation"));const list=el('div','finance-list');const draw=()=>{list.replaceChildren(...types().map(t=>{const r=el('div','finance-row'),left=el('div');left.append(el('strong','',t.label),el('span','muted',`${money(t.amount)} • ${t.kind}`));r.append(left);if(canWrite()&&!DEFAULT_TYPES.some(d=>d.id===t.id)){const del=btn('Retirer',()=>{const next=(AppState.data.financeSettings?.paymentTypes||[]).filter(x=>x.id!==t.id);persist({financeSettings:{...(AppState.data.financeSettings||{}),paymentTypes:next}});window.CHEBSEL?.rerender?.()});r.append(del)}return r}))};draw();
 if(canWrite()){const add=el('form','form-grid');add.innerHTML='<label>Nom du nouveau type<input name="label" placeholder="Ex. Uniforme"></label><label>Montant<input name="amount" type="number" min="0" value="0"></label><label>Catégorie<select name="kind"><option value="contribution">Cotisation</option><option value="fine">Amende</option><option value="other">Autre</option></select></label><div class="wide dialog-actions"><button class="btn secondary">Ajouter le type</button></div>';add.onsubmit=e=>{e.preventDefault();const fd=new FormData(add),label=String(fd.get('label')||'').trim();if(!label)return;const id=`custom_${Date.now().toString(36)}`,next=[...(AppState.data.financeSettings?.paymentTypes||[]),{id,label,amount:Number(fd.get('amount')||0),kind:String(fd.get('kind')||'other')}];persist({financeSettings:{...(AppState.data.financeSettings||{}),paymentTypes:next}});window.CHEBSEL?.rerender?.()};custom.append(list,add)}else custom.append(list);w.append(custom);return w
}

export function renderDebtors(){const w=page('Débiteurs','Dette cumulée calculée automatiquement à partir du dû et du payé.');const q=el('input','finance-search');q.type='search';q.placeholder='Rechercher un membre…';const list=el('div','debtor-list');w.append(q,list);const render=()=>{const s=q.value.toLowerCase().trim(),rows=(AppState.data.members||[]).map(m=>({m,b:memberBalance(m.id)})).filter(x=>x.b.balance>0&&(!s||nameOf(x.m.id).toLowerCase().includes(s))).sort((a,b)=>b.b.balance-a.b.balance);list.replaceChildren(...(rows.length?rows.map(({m,b})=>{const c=el('div','panel debtor-row'),x=el('div');x.append(el('strong','',nameOf(m.id)),el('div','muted',`Dû ${money(b.due)} • Payé ${money(b.paid)}`));c.append(x,el('b','debt-amount',money(b.balance)));return c}):[el('div','panel empty-state','Aucun débiteur.')]))};q.oninput=render;render();return w}
export function renderExpenses(){const w=page('Dépenses','Registre des dépenses de la chorale.');if(canWrite())w.querySelector('.page-head').append(btn('+ Ajouter une dépense',()=>openExpenseDialog(),true));const rows=expenses().slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))),list=el('div','finance-list');list.replaceChildren(...(rows.length?rows.map(x=>{const c=el('div','panel finance-row'),left=el('div');left.append(el('strong','',x.label||x.description||x.category||'Dépense'),el('div','muted',`${x.date||'—'}${x.note?' • '+x.note:''}`));c.append(left,el('b','',money(x.amount)));return c}):[el('div','panel empty-state','Aucune dépense enregistrée.')]));w.append(list);return w}
function openExpenseDialog(){if(!canWrite())return;const d=document.createElement('dialog');d.className='member-dialog';d.innerHTML=`<form><div class="dialog-head"><h2>Nouvelle dépense</h2><button type="button" class="icon-close">×</button></div><div class="form-grid"><label>Date<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Libellé<input name="label" required></label><label>Montant<input name="amount" type="number" min="0" required></label><label class="wide">Observation<textarea name="note"></textarea></label></div><div class="dialog-actions"><button class="btn primary">Enregistrer</button></div></form>`;document.body.append(d);d.querySelector('.icon-close').onclick=()=>{d.close();d.remove()};d.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),x={id:uid(),date:String(fd.get('date')),label:String(fd.get('label')).trim(),amount:Number(fd.get('amount')||0),note:String(fd.get('note')||'').trim(),createdAt:new Date().toISOString()};persist({expenses:[...expenses(),x]});d.close();d.remove();window.CHEBSEL?.rerender?.()};d.showModal()}
export function renderFinanceHistory(){const w=page('Historique / Histogramme','Vue mensuelle des encaissements, créances et dépenses.');const month=document.createElement('input');month.type='month';month.value=monthNow();month.className='finance-search';const box=el('div','finance-history');w.append(month,box);const render=()=>{const m=month.value,es=entries().filter(e=>String(e.date||'').startsWith(m)),xs=expenses().filter(e=>String(e.date||'').startsWith(m)),due=es.reduce((s,e)=>s+Number(e.due||0),0),paid=es.reduce((s,e)=>s+Number(e.paid||0),0),expense=xs.reduce((s,e)=>s+Number(e.amount||0),0),debt=Math.max(0,due-paid),max=Math.max(1,due,paid,debt,expense);box.innerHTML='';const stats=el('div','member-stats');[['Dû',money(due)],['Payé',money(paid)],['Créances',money(debt)],['Dépenses',money(expense)],['Solde caisse',money(paid-expense)]].forEach(([k,v])=>{const x=el('div','member-stat');x.append(el('b','',v),el('span','',k));stats.append(x)});const chart=el('div','bar-chart');[['Dû',due],['Payé',paid],['Créances',debt],['Dépenses',expense]].forEach(([k,v])=>{const r=el('div','bar-row');r.innerHTML=`<span>${k}</span><div class="bar-track"><i style="width:${Math.round(v/max*100)}%"></i></div><b>${money(v)}</b>`;chart.append(r)});box.append(stats,chart)};month.onchange=render;render();return w}
export function renderFinanceReports(){const w=page('Rapport financier','Synthèse libre par période.');const controls=el('div','panel report-controls');controls.innerHTML=`<label>Du <input id="finFrom" type="date"></label><label>Au <input id="finTo" type="date"></label><button id="finGenerate" class="btn primary">Générer</button>`;const out=el('div','finance-report');w.append(controls,out);controls.querySelector('#finGenerate').onclick=()=>{const a=controls.querySelector('#finFrom').value,z=controls.querySelector('#finTo').value,inside=d=>(!a||d>=a)&&(!z||d<=z),es=entries().filter(e=>inside(String(e.date||''))),xs=expenses().filter(e=>inside(String(e.date||''))),due=es.reduce((s,e)=>s+Number(e.due||0),0),paid=es.reduce((s,e)=>s+Number(e.paid||0),0),ex=xs.reduce((s,e)=>s+Number(e.amount||0),0),debt=Math.max(0,due-paid);out.innerHTML=`<div class="member-stats"><div class="member-stat"><b>${money(due)}</b><span>Total dû</span></div><div class="member-stat"><b>${money(paid)}</b><span>Total encaissé</span></div><div class="member-stat"><b>${money(debt)}</b><span>Créances</span></div><div class="member-stat"><b>${money(ex)}</b><span>Dépenses</span></div><div class="member-stat"><b>${money(paid-ex)}</b><span>Solde</span></div></div>`};return w}
export function registerFinanceRoutes(registerRoute){registerRoute('payment-entry',renderPaymentEntry);registerRoute('finance-settings',renderFinanceSettings);registerRoute('debtors',renderDebtors);registerRoute('expenses',renderExpenses);registerRoute('finance-history',renderFinanceHistory);registerRoute('finance-reports',renderFinanceReports)}
