let deferredPrompt=null;
let initialized=false;
const isStandalone=()=>window.matchMedia?.('(display-mode: standalone)').matches===true||window.navigator.standalone===true;
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent||'');
const $=id=>document.getElementById(id);
function showInstallControls(){const show=!isStandalone();const banner=$('installBanner'),roleBtn=$('installFromRoleBtn');if(banner)banner.hidden=!show;if(roleBtn)roleBtn.hidden=!show}
function hideInstallControls(){const banner=$('installBanner'),roleBtn=$('installFromRoleBtn');if(banner)banner.hidden=true;if(roleBtn)roleBtn.hidden=true}
function instructions(){document.getElementById('installHelpDialogV2')?.remove();const d=document.createElement('dialog');d.id='installHelpDialogV2';d.className='member-dialog';const ios=isIOS();d.innerHTML=`<div class="dialog-head"><h2>Installer CHEBSEL</h2><button type="button" class="icon-close" data-close>×</button></div><p>${ios?'Sou iPhone/iPad, ouvri bouton <b>Partager</b> nan Safari epi chwazi <b>Sur l’écran d’accueil</b>.':'Nan meni navigatè a, chwazi <b>Installer l’application</b> oswa <b>Ajouter à l’écran d’accueil</b>.'}</p><p class="muted">Apre enstalasyon an, CHEBSEL ap ouvri tankou yon aplikasyon sou aparèy la.</p><div class="dialog-actions"><button type="button" class="btn primary" data-close>Compris</button></div>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{d.close();d.remove()});d.addEventListener('cancel',()=>d.remove(),{once:true});d.showModal()}
async function requestInstall(){if(isStandalone()){hideInstallControls();return}if(deferredPrompt){const p=deferredPrompt;deferredPrompt=null;await p.prompt();const choice=await p.userChoice.catch(()=>null);if(choice?.outcome==='accepted')hideInstallControls();else showInstallControls();return}instructions()}
export function initInstall(){if(initialized)return;initialized=true;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;showInstallControls()});window.addEventListener('appinstalled',()=>{deferredPrompt=null;hideInstallControls()});$('installAppBtn')?.addEventListener('click',requestInstall);$('installFromRoleBtn')?.addEventListener('click',requestInstall);if(!isStandalone())showInstallControls()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initInstall,{once:true});else initInstall();
