import {AppState} from './app-state.js';
import {saveAppSettings} from './storage.js';

const el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const money=v=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0))+' G';
const today=()=>new Date().toISOString().slice(0,10);
const monthNow=()=>today().slice(0,7);
const monthRange=m=>({from:`${m}-01`,to:`${m}-${String(new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate()).padStart(2,'0')}`});
const validEntry=e=>!e?.voided&&!e?.cancelled&&e?.status!=='cancelled';
const validExpense=e=>!e?.voided&&!e?.cancelled&&!e?.deletedAt&&e?.status!=='cancelled';
const nameOf=id=>{const m=(AppState.data.members||[]).find(x=>String(x.id)===String(id));return m?[m.first,m.last].filter(Boolean).join(' '):'Membre inconnu'};
const page=(title,sub='')=>{const w=el('section','page'),h=el('div','page-head');h.append(el('h1','',title));if(sub)h.append(el('p','muted',sub));w.append(h);return w};
const btn=(text,fn,primary=false)=>{const b=el('button',`btn ${primary?'primary':'secondary'}`,text);b.type='button';b.onclick=fn;return b};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalizeRange(a,z){if(!a||!z)return null;return a<=z?{from:a,to:z}:{from:z,to:a}}
function punctualityData(from,to){const calls=(AppState.data.attendance||[]).filter(c=>{const d=String(c?.date||'').slice(0,10);return d>=from&&d<=to}).sort((a,b)=>String(a.date).localeCompare(String(b.date)));let marked=0,present=0,late=0,absent=0,anm=0,anmp=0,rnm=0;const details=[];for(const c of calls){let cp=0,cl=0,ca=0,cm=0;for(const r of Object.values(c?.records||{})){const st=String(r?.status||'').toUpperCase();if(!st)continue;marked++;cm++;if(st==='P'){present++;cp++}else if(['R','RM','RNM'].includes(st)){late++;cl++;if(st==='RNM')rnm++}else if(['A','AM','ANM','ANMP'].includes(st)){absent++;ca++;if(st==='ANM')anm++;if(st==='ANMP')anmp++}}details.push({date:String(c.date||''),activity:c.activity||c.title||c.type||'Activité',marked:cm,present:cp,late:cl,absent:ca,attendanceRate:cm?Math.round((cp+cl)/cm*100):0,punctualityRate:(cp+cl)?Math.round(cp/(cp+cl)*100):0})}return{from,to,calls:calls.length,marked,present,late,absent,anm,anmp,rnm,attendanceRate:marked?Math.round((present+late)/marked*100):0,punctualityRate:(present+late)?Math.round(present/(present+late)*100):0,details}}
function financeData(from,to){const income=(AppState.data.finance||[]).filter(e=>{const d=String(e?.date||'').slice(0,10);return validEntry(e)&&d>=from&&d<=to&&Number(e?.paid??e?.amountPaid??0)>0}).map(e=>({date:String(e.date||''),source:nameOf(e.memberId??e.member_id),type:e.typeLabel||e.label||'Paiement',reference:e.reference||e.ref||e.id||'',amount:Number(e.paid??e.amountPaid??0)})).sort((a,b)=>a.date.localeCompare(b.date));const expenses=(AppState.data.expenses||[]).filter(e=>{const d=String(e?.date||'').slice(0,10);return validExpense(e)&&d>=from&&d<=to}).map(e=>({date:String(e.date||''),reason:e.reason||e.label||e.description||'Dépense',category:e.category||'',reference:e.reference||'',amount:Number(e.amount||0)})).sort((a,b)=>a.date.localeCompare(b.date));const totalIn=income.reduce((s,x)=>s+x.amount,0),totalOut=expenses.reduce((s,x)=>s+x.amount,0);return{from,to,income,expenses,totalIn,totalOut,net:totalIn-totalOut}}
function actionBar(printFn,jpegFn){const a=el('div','report-actions');a.append(btn('🖨️ Imprimer',printFn),btn('🖼️ Enregistrer JPEG',jpegFn));return a}
function printNode(node,title){if(!node)return;const w=window.open('','_blank');if(!w)return alert('Le navigateur a bloqué la fenêtre d’impression.');w.document.write(`<html><head><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:7px;text-align:left}.report-kpis{display:flex;gap:10px;flex-wrap:wrap}.report-kpi{border:1px solid #ccc;padding:10px;border-radius:8px;min-width:130px}.report-actions{display:none}</style></head><body>${node.outerHTML}</body></html>`);w.document.close();w.focus();w.print()}
function wrap(ctx,text,x,y,max,line){const words=String(text).split(' ');let s='';for(const word of words){const test=s?`${s} ${word}`:word;if(ctx.measureText(test).width>max&&s){ctx.fillText(s,x,y);y+=line;s=word}else s=test}if(s)ctx.fillText(s,x,y);return y}
function jpegReport({title,period,kpis,headers,rows,filename}){const W=1500,rowH=42,headH=390,H=Math.max(1000,headH+(rows.length+2)*rowH+120),c=document.createElement('canvas');c.width=W;c.height=H;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,W,H);g.fillStyle='#102644';g.fillRect(0,0,W,170);g.fillStyle='#fff';g.font='700 38px Arial';g.fillText(title,60,72);g.font='23px Arial';g.fillText(period,60,118);g.fillStyle='#111';g.font='700 22px Arial';let x=60,y=220;for(const [k,v] of kpis){g.fillText(`${k}:`,x,y);g.font='22px Arial';g.fillText(String(v),x+170,y);x+=450;if(x>1100){x=60;y+=46}g.font='700 22px Arial'}y=Math.max(330,y+70);const widths=headers.map((_,i)=>i===0?150:(W-120-150)/(headers.length-1));g.fillStyle='#e8edf3';g.fillRect(55,y-30,W-110,42);g.fillStyle='#111';g.font='700 18px Arial';let xx=65;headers.forEach((h,i)=>{g.fillText(String(h),xx,y);xx+=widths[i]});g.font='17px Arial';y+=44;for(const row of rows){xx=65;row.forEach((v,i)=>{let txt=String(v??'');const max=Math.max(8,Math.floor(widths[i]/9));if(txt.length>max)txt=txt.slice(0,max-1)+'…';g.fillText(txt,xx,y);xx+=widths[i]});g.strokeStyle='#ddd';g.beginPath();g.moveTo(55,y+11);g.lineTo(W-55,y+11);g.stroke();y+=rowH}g.fillStyle='#667085';g.font='16px Arial';g.fillText('CHEBSEL • '+new Date().toLocaleString('fr-FR'),60,H-50);const a=document.createElement('a');a.download=filename;a.href=c.toDataURL('image/jpeg',0.94);a.click()}
function reportControls(onGenerate){const p=el('div','panel report-controls');p.innerHTML=`<label>Du <input name="from" type="date"></label><label>Au <input name="to" type="date"></label>`;const r=monthRange(monthNow());p.elements?.from;const from=p.querySelector('[name=from]'),to=p.querySelector('[name=to]');from.value=r.from;to.value=Math.min(today(),r.to);p.append(btn('Générer',()=>{const x=normalizeRange(from.value,to.value);if(!x)return alert('Choisissez une période valide.');onGenerate(x.from,x.to)},true));return p}
function renderPunctualityResult(out,d){out.innerHTML=`<div class="panel report-printable"><h2>Rapport de ponctualité CHEBSEL</h2><p class="muted">Période : ${esc(d.from)} au ${esc(d.to)}</p><div class="report-kpis"><div class="report-kpi"><b>${d.calls}</b><span>Activités</span></div><div class="report-kpi"><b>${d.attendanceRate}%</b><span>Présence</span></div><div class="report-kpi"><b>${d.punctualityRate}%</b><span>Ponctualité</span></div><div class="report-kpi"><b>${d.late}</b><span>Retards</span></div><div class="report-kpi"><b>${d.absent}</b><span>Absences</span></div><div class="report-kpi"><b>${d.anm+d.anmp}</b><span>Abs. non motivées</span></div></div><h3>Détail par activité</h3><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Activité</th><th>Marqués</th><th>Présents</th><th>Retards</th><th>Absences</th><th>Présence</th><th>Ponctualité</th></tr></thead><tbody>${d.details.length?d.details.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.activity)}</td><td>${x.marked}</td><td>${x.present}</td><td>${x.late}</td><td>${x.absent}</td><td>${x.attendanceRate}%</td><td>${x.punctualityRate}%</td></tr>`).join(''):'<tr><td colspan="8">Aucune activité.</td></tr>'}</tbody></table></div></div>`;const node=out.querySelector('.report-printable');out.prepend(actionBar(()=>printNode(node,'Rapport de ponctualité CHEBSEL'),()=>jpegReport({title:'CHEBSEL — RAPPORT DE PONCTUALITÉ',period:`${d.from} au ${d.to}`,kpis:[['Activités',d.calls],['Présence',d.attendanceRate+'%'],['Ponctualité',d.punctualityRate+'%'],['Retards',d.late],['Absences',d.absent]],headers:['Date','Activité','Marqués','Présents','Retards','Absences','Présence','Ponctualité'],rows:d.details.map(x=>[x.date,x.activity,x.marked,x.present,x.late,x.absent,x.attendanceRate+'%',x.punctualityRate+'%']),filename:`Rapport_ponctualite_CHEBSEL_${d.from}_${d.to}.jpg`})))}
function renderFinanceResult(out,d){out.innerHTML=`<div class="panel report-printable"><h2>Rapport financier CHEBSEL</h2><p class="muted">Période : ${esc(d.from)} au ${esc(d.to)}</p><div class="report-kpis"><div class="report-kpi"><b>${money(d.totalIn)}</b><span>Entrées</span></div><div class="report-kpi"><b>${money(d.totalOut)}</b><span>Dépenses</span></div><div class="report-kpi"><b>${money(d.net)}</b><span>Solde net</span></div></div><h3>Entrées</h3><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Source</th><th>Type</th><th>Référence</th><th>Montant</th></tr></thead><tbody>${d.income.length?d.income.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.source)}</td><td>${esc(x.type)}</td><td>${esc(x.reference||'—')}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5">Aucune entrée.</td></tr>'}</tbody></table></div><h3>Dépenses</h3><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Date</th><th>Motif</th><th>Catégorie</th><th>Référence</th><th>Montant</th></tr></thead><tbody>${d.expenses.length?d.expenses.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.reason)}</td><td>${esc(x.category||'—')}</td><td>${esc(x.reference||'—')}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="5">Aucune dépense.</td></tr>'}</tbody></table></div></div>`;const node=out.querySelector('.report-printable');out.prepend(actionBar(()=>printNode(node,'Rapport financier CHEBSEL'),()=>jpegReport({title:'CHEBSEL — RAPPORT FINANCIER',period:`${d.from} au ${d.to}`,kpis:[['Entrées',money(d.totalIn)],['Dépenses',money(d.totalOut)],['Solde net',money(d.net)]],headers:['Date','Type','Source / Motif','Référence','Montant'],rows:[...d.income.map(x=>[x.date,'Entrée',x.source,x.reference||'—',money(x.amount)]),...d.expenses.map(x=>[x.date,'Dépense',x.reason,x.reference||'—',money(x.amount)])].sort((a,b)=>a[0].localeCompare(b[0])),filename:`Rapport_financier_CHEBSEL_${d.from}_${d.to}.jpg`})))}
export function renderPunctualityReports(){const w=page('Rapports de ponctualité','Rapport détaillé pour toute période, avec impression et enregistrement JPEG.');const out=el('div','report-output');w.append(reportControls((a,z)=>renderPunctualityResult(out,punctualityData(a,z))),out);if(AppState.role==='secretary'){const m=el('div','panel monthly-submit');m.append(el('h3','','Rapport mensuel officiel'),el('p','muted','Préparer le rapport du mois et l’envoyer au Président pour validation.'));const input=document.createElement('input');input.type='month';input.value=monthNow();m.append(input,btn('Préparer et soumettre au Président',()=>prepareMonthly('punctuality',input.value),true));w.append(m)}return w}
export function renderFinanceReports(){const w=page('Rapports financiers','Rapport financier détaillé par période, avec impression et enregistrement JPEG.');const out=el('div','report-output');w.append(reportControls((a,z)=>renderFinanceResult(out,financeData(a,z))),out);if(AppState.role==='treasurer'){const m=el('div','panel monthly-submit');m.append(el('h3','','Rapport mensuel officiel'),el('p','muted','Préparer le rapport du mois et l’envoyer au Président pour validation.'));const input=document.createElement('input');input.type='month';input.value=monthNow();m.append(input,btn('Préparer et soumettre au Président',()=>prepareMonthly('finance',input.value),true));w.append(m)}return w}
function monthlyStore(){return AppState.data.settings?.monthlyReports&&typeof AppState.data.settings.monthlyReports==='object'?AppState.data.settings.monthlyReports:{}}
function saveMonthly(store){const next=saveAppSettings({monthlyReports:store});AppState.data.settings=next}
function prepareMonthly(kind,month){if(!month)return;const r=monthRange(month),store={...monthlyStore()},rec={...(store[month]||{})},data=kind==='finance'?financeData(r.from,r.to):punctualityData(r.from,r.to);rec[kind]={status:'prepared',preparedAt:new Date().toISOString(),preparedBy:AppState.user?.name||'',data};delete rec.global;store[month]=rec;saveMonthly(store);alert('Rapport mensuel préparé et envoyé au Président pour validation.');window.CHEBSEL?.rerender?.()}
function validateMonthly(kind,month){const store={...monthlyStore()},rec={...(store[month]||{})},x=rec[kind];if(!x)return;rec[kind]={...x,status:'validated',validatedAt:new Date().toISOString(),validatedBy:AppState.user?.name||'Président'};delete rec.global;store[month]=rec;saveMonthly(store);window.CHEBSEL?.rerender?.()}
function generateGlobal(month){const store={...monthlyStore()},rec={...(store[month]||{})};if(rec.punctuality?.status!=='validated'||rec.finance?.status!=='validated')return alert('Prezidan an dwe valide toude rapò yo anvan li jenere rapò global la.');rec.global={status:'generated',generatedAt:new Date().toISOString(),generatedBy:AppState.user?.name||'Président',punctuality:rec.punctuality.data,finance:rec.finance.data};store[month]=rec;saveMonthly(store);window.CHEBSEL?.rerender?.()}
function monthlyStatus(x,label){const c=el('div','panel monthly-status'),copy=el('div');copy.append(el('h3','',label),el('p','muted',!x?'Pa ko resevwa':x.status==='validated'?`Valide • ${new Date(x.validatedAt).toLocaleString('fr-FR')}`:`Prepare • ${new Date(x.preparedAt).toLocaleString('fr-FR')}`));c.append(copy);return c}
function renderGlobalResult(container,month,g){const p=g.punctuality,f=g.finance;container.innerHTML=`<div class="panel report-printable"><h2>Rapport global mensuel CHEBSEL</h2><p class="muted">Mois : ${esc(month)}</p><div class="report-kpis"><div class="report-kpi"><b>${money(f.totalIn)}</b><span>Entrées</span></div><div class="report-kpi"><b>${money(f.totalOut)}</b><span>Dépenses</span></div><div class="report-kpi"><b>${money(f.net)}</b><span>Solde net</span></div><div class="report-kpi"><b>${p.attendanceRate}%</b><span>Présence</span></div><div class="report-kpi"><b>${p.punctualityRate}%</b><span>Ponctualité</span></div></div><h3>Synthèse ponctualité</h3><p>${p.calls} activité(s), ${p.present} présence(s), ${p.late} retard(s), ${p.absent} absence(s).</p><h3>Synthèse financière</h3><p>${money(f.totalIn)} d’entrées, ${money(f.totalOut)} de dépenses, solde net ${money(f.net)}.</p></div>`;const node=container.querySelector('.report-printable');container.prepend(actionBar(()=>printNode(node,'Rapport global mensuel CHEBSEL'),()=>jpegReport({title:'CHEBSEL — RAPPORT GLOBAL MENSUEL',period:month,kpis:[['Entrées',money(f.totalIn)],['Dépenses',money(f.totalOut)],['Solde',money(f.net)],['Présence',p.attendanceRate+'%'],['Ponctualité',p.punctualityRate+'%']],headers:['Indicateur','Valeur'],rows:[['Activités',p.calls],['Présences',p.present],['Retards',p.late],['Absences',p.absent],['Entrées',money(f.totalIn)],['Dépenses',money(f.totalOut)],['Solde net',money(f.net)]],filename:`Rapport_global_mensuel_CHEBSEL_${month}.jpg`})))}
export function renderMonthlyReports(){if(AppState.role!=='president'){const w=page('Rapports Mensuels');w.append(el('div','panel','Accès réservé au Président.'));return w}const w=page('Rapports Mensuels','Validation des rapports du Secrétaire et du Trésorier, puis génération du rapport global mensuel.');const pick=el('div','panel admin-controls'),month=document.createElement('input');month.type='month';month.value=monthNow();pick.append(month);w.append(pick);const body=el('div','monthly-workflow');w.append(body);const draw=()=>{body.innerHTML='';const rec=monthlyStore()[month.value]||{},p=monthlyStatus(rec.punctuality,'Rapport mensuel — Ponctualité'),f=monthlyStatus(rec.finance,'Rapport mensuel — Finance');if(rec.punctuality?.status==='prepared')p.append(btn('Valider le rapport ponctualité',()=>validateMonthly('punctuality',month.value),true));if(rec.finance?.status==='prepared')f.append(btn('Valider le rapport financier',()=>validateMonthly('finance',month.value),true));if(rec.punctuality?.data)p.append(btn('Voir le détail',()=>{const box=el('div','report-output');body.append(box);renderPunctualityResult(box,rec.punctuality.data)}));if(rec.finance?.data)f.append(btn('Voir le détail',()=>{const box=el('div','report-output');body.append(box);renderFinanceResult(box,rec.finance.data)}));body.append(p,f);const both=rec.punctuality?.status==='validated'&&rec.finance?.status==='validated';if(both)body.append(btn(rec.global?'Regénérer le rapport global mensuel':'Générer le rapport global mensuel',()=>generateGlobal(month.value),true));if(rec.global){const g=el('div','report-output');body.append(g);renderGlobalResult(g,month.value,rec.global)}};month.onchange=draw;draw();return w}
