from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old="async function cloudPilotSync(){await repairV158Outbox();if(isVisitor()){alert('Accès réservé aux responsables.');return}if(!navigator.onLine){alert('Pas d’Internet. Les modifications restent locales.');return}try{cloudState.textContent='Synchronisation…';await syncReadyReconcilePilot(true);const p=await getCloudProfile(),org=p.organization_id;const pm=await pushPilotEntity('members','members',cloudMemberPayload,org),pc=await pushPilotEntity('calendar_events','calendar_events',cloudCalendarPayload,org),rm=await pullCloudMembers(org),rc=await pullCloudCalendar(org);await syncReadyReconcilePilot(false);const out=await idbAll('outbox');for(const op of out){if(['members','calendar_events'].includes(op.entity)&&op.status==='pending'){op.status='synced';op.syncedAt=syncNowISO();await idbPut('outbox',op)}}saveJSON(CLOUD_META_KEY,{...(safeParse(CLOUD_META_KEY)||{}),lastSyncAt:syncNowISO(),lastSummary:{pm,pc,rm,rc}});refreshHome();updateCloudUI();updateSyncReadyUI();alert('Synchronisation pilote terminée.')}catch(e){alert('Synchronisation cloud impossible : '+e.message);updateCloudUI()}}"
new="async function cloudPilotSync(){if(isVisitor()){alert('Accès réservé aux responsables.');return}if(!navigator.onLine){alert('Pas d’Internet. Les modifications restent locales.');return}try{cloudState.textContent='Préparation locale…';await repairV159LocalState();const session=await cloudSessionInfo();if(!session)throw new Error('Session cloud absente. Reconnectez-vous au cloud.');cloudState.textContent='Vérification du profil…';const p=await getCloudProfile(),org=p.organization_id;await syncReadyReconcilePilot(false);cloudState.textContent='Envoi des membres…';const pm=await pushPilotEntity('members','members',cloudMemberPayload,org);cloudState.textContent='Envoi du calendrier…';const pc=await pushPilotEntity('calendar_events','calendar_events',cloudCalendarPayload,org);cloudState.textContent='Réception des membres…';const rm=await pullCloudMembers(org);cloudState.textContent='Réception du calendrier…';const rc=await pullCloudCalendar(org);await repairV159LocalState();await syncReadyReconcilePilot(false);const out=await idbAll('outbox');for(const op of out){if(['members','calendar_events'].includes(op.entity)){await idbDelete('outbox',op.id)}}saveJSON(CLOUD_META_KEY,{...(safeParse(CLOUD_META_KEY)||{}),lastSyncAt:syncNowISO(),lastSummary:{pm,pc,rm,rc}});cloudState.textContent='🟢 Synchronisé';refreshHome();await updateCloudUI();await updateSyncReadyUI();alert(`Synchronisation pilote terminée. Membres envoyés: ${pm}; reçus: ${rm}. Calendrier envoyé: ${pc}; reçu: ${rc}.`)}catch(e){cloudState.textContent='🔴 Erreur sync';alert('Synchronisation cloud impossible : '+e.message);updateCloudUI()}}"
if old not in s:
    raise SystemExit('cloudPilotSync v1.5.9 block not found')
s=s.replace(old,new,1)
s=s.replace('CHEBSEL v1.5.9 — Centre de gestion','CHEBSEL v1.5.10 — Centre de gestion')
s=s.replace('>v1.5.9<','>v1.5.10<')
p.write_text(s,encoding='utf-8')
sw=Path('sw.js')
x=sw.read_text(encoding='utf-8').replace('chebsel-pwa-stable-v159','chebsel-pwa-stable-v1510')
sw.write_text(x,encoding='utf-8')
