from pathlib import Path
import re
p=Path('index.html');s=p.read_text(encoding='utf-8')
pat=r"function openVisitorDebtorProfile\(mid\)\{.*?\n\}\nfunction openProfileFromDebtors\(mid\)\{"
rep="""function openVisitorDebtorProfile(mid){
 const x=(publicVisitorSnapshot()?.debtors||[]).find(d=>String(d.member_id||'')===String(mid||''));if(!x)return;
 const a=x.attendance_stats||{},ah=x.attendance_history||[],fh=x.financial_history||[],ph=x.payment_history||[];
 const due=fh.reduce((t,e)=>t+Number(e.due||0),0),paid=fh.reduce((t,e)=>t+Number(e.paid||0),0),activities=Number(a.activities||0),present=Number(a.present||0),late=Number(a.late||0),absent=Number(a.absent||0),rate=activities?((present/activities)*100).toFixed(1).replace('.',',')+' %':'0,0 %';
 debtorsView.classList.remove('open');profileView.classList.add('open');
 profileBody.innerHTML=`<div class="profilePanel"><div class="profileTitle"><div><h3>${escapeHtml(x.name||'—')}</h3><div class="memberMeta">N° ${escapeHtml(x.member_no||'—')} • Fiche membre — lecture seule</div></div><span class="status ${x.active!==false?'active':''}">${x.active!==false?'Actif':'Inactif'}</span></div><div class="memberStats"><div class="mini"><b>${activities}</b><span>Activités</span></div><div class="mini"><b>${present}</b><span>Présences</span></div><div class="mini"><b>${late}</b><span>Retards</span></div><div class="mini"><b>${rate}</b><span>Taux</span></div><div class="mini"><b>${absent}</b><span>Absences</span></div><div class="mini"><b>${money(due)}</b><span>Dû</span></div><div class="mini"><b>${money(paid)}</b><span>Payé</span></div><div class="mini"><b>${money(Number(x.debt||0))}</b><span>Dette</span></div></div></div><div class="profilePanel"><h3>Historique financier</h3>${fh.length?fh.map(e=>`<div class="ledgerRow"><div><div class="ledgerMain">${escapeHtml(e.label||e.type||'Écriture')}</div><div class="ledgerMeta">${escapeHtml(e.date||'')} • Dû ${money(e.due||0)} • Payé ${money(e.paid||0)}</div></div><div>${Number(e.balance||0)>0?'<span class="debtTag">Solde '+money(e.balance)+'</span>':'<span class="paidTag">Soldé</span>'}</div></div>`).join(''):'<div class="empty">Aucune écriture financière.</div>'}</div><div class="profilePanel"><h3>Paiements enregistrés</h3>${ph.length?ph.map(e=>`<div class="ledgerRow"><div><div class="ledgerMain">${money(e.amount||0)}</div><div class="ledgerMeta">${escapeHtml(e.date||'')} ${e.receipt_number?'• Reçu '+escapeHtml(e.receipt_number):''}</div></div></div>`).join(''):'<div class="empty">Aucun paiement enregistré.</div>'}</div><div class="profilePanel"><h3>Historique de présence</h3>${ah.length?ah.map(e=>`<div class="ledgerRow"><div><div class="ledgerMain">${escapeHtml(e.activity||'Activité')}</div><div class="ledgerMeta">${escapeHtml(e.date||'')} • ${escapeHtml(({P:'Présent',RM:'Retard motivé',R:'Retard motivé',RNM:'Retard non motivé',AM:'Absence motivée',A:'Absence motivée',ANM:'Absence non motivée',ANMP:'Absence non motivée — prestation'})[String(e.status||'').toUpperCase()]||e.status||'Non renseigné')}</div></div></div>`).join(''):'<div class="empty">Aucun historique de présence.</div>'}</div>`;
}
function openProfileFromDebtors(mid){"""
s,n=re.subn(pat,rep,s,count=1,flags=re.S);assert n==1
block=re.search(r"function openVisitorDebtorProfile\(mid\)\{.*?\n\}",s,re.S).group(0)
assert 'Enregistrer un paiement' not in block and 'Historique financier' in block and 'Historique de présence' in block
p.write_text(s,encoding='utf-8')
